### ISSUE TITLE
Jedi-vim not show any completion candidate

### ISSUE THREAD

**Issue by fuzhen011** [davidhalter/jedi-vim#1004]
### Jedi-vim not show any completion candidate

I have Jedi-vim installed via Bundle but it doesn't work when I editing python files. I have Jedi installed in my system. I was trying to figure out what is wrong but I can't find anything wrong with the output from :JediDebugInfo command.

It may not be able to reproduce, probably it's related to my environment, but I went through all the documents that I could find and cannot figure out a way to get more debug information why it doesn't work.

##### jedi-vim version

 - jedi-vim git version: 0.10.0-36-ge83112f
 - jedi git submodule status:  3ad3dc08b8bf9d749b2d0d9fca038657711c82f2 pythonx/jedi (v0.16.0-11-g3ad3dc08)
 - parso git submodule status:  c864ca60d1a2f36524a4f79013a7de223e65e19d pythonx/parso (v0.6.0)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/usr/bin/python3`
 - global sys.version: `3.6.9 (default, Nov  7 2019, 10:44:02), [GCC 8.3.0]`
 - global site module: `/usr/lib/python3.6/site.py`

##### Jedi

 - path: `/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.16.1

##### Jedi environment: <SameEnvironment: 3.6.9 in /usr>

 - executable: /usr/bin/python3
 - sys_path:
    - `/home/zhfu/work/gconfig/scripts`
    - `/home/zhfu/work/pybgapi`
    - `/usr/lib/python36.zip`
    - `/usr/lib/python3.6`
    - `/usr/lib/python3.6/lib-dynload`
    - `/home/zhfu/.local/lib/python3.6/site-packages`
    - `/usr/local/lib/python3.6/dist-packages`
    - `/usr/lib/python3/dist-packages`

##### Known environments

 - <Environment: 3.6.9 in /usr> (/usr/bin/python3.6)

 - <Environment: 2.7.17 in /usr> (/usr/bin/python2.7)

##### Settings

```
  omnifunc=jedi#completions
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim line 738
  completeopt=menuone,longest,preview
	Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim line 716
```

#### :version
```

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 20 2020 10:15:18)
Included patches: 1-416
Compiled by zhfu@zhfu-7480
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +dnd               +localmap          +printer           +textprop
+arabic            -ebcdic            +lua               +profile           +timers
+autocmd           +emacs_tags        +menu              -python            +title
+autochdir         +eval              +mksession         +python3           +toolbar
-autoservername    +ex_extra          +modify_fname      +quickfix          +user_commands
+balloon_eval      +extra_search      +mouse             +reltime           +vartabs
+balloon_eval_term -farsi             +mouseshape        +rightleft         +vertsplit
+browse            +file_in_path      +mouse_dec         +ruby              +virtualedit
++builtin_terms    +find_in_path      -mouse_gpm         +scrollbind        +visual
+byte_offset       +float             -mouse_jsbterm     +signs             +visualextra
+channel           +folding           +mouse_netterm     +smartindent       +viminfo
+cindent           -footer            +mouse_sgr         +sound             +vreplace
+clientserver      +fork()            -mouse_sysmouse    +spell             +wildignore
+clipboard         +gettext           +mouse_urxvt       +startuptime       +wildmenu
+cmdline_compl     -hangul_input      +mouse_xterm       +statusline        +windows
+cmdline_hist      +iconv             +multi_byte        -sun_workshop      +writebackup
+cmdline_info      +insert_expand     +multi_lang        +syntax            +X11
+comments          +job               -mzscheme          +tag_binary        -xfontset
+conceal           +jumplist          +netbeans_intg     -tag_old_static    +xim
+cryptv            +keymap            +num64             -tag_any_white     +xpm
+cscope            +lambda            +packages          -tcl               +xsmp_interact
+cursorbind        +langmap           +path_extra        +termguicolors     +xterm_clipboard
+cursorshape       +libcall           +perl              +terminal          -xterm_save
+dialog_con_gui    +linebreak         +persistent_undo   +terminfo          
+diff              +lispindent        +popupwin          +termresponse      
+digraphs          +listcmds          +postscript        +textobjects       
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
 f-b for $VIMRUNTIME: "/usr/local/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lnsl  -lselinux  -lcanberra -ldl  -L/usr/lib -llua5.1 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm  -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm     
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
    completions = script.completions()
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 214, in completions
    return self.complete(*self._pos, fuzzy=fuzzy)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 456, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 202, in complete
    return self._complete(line, column, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 210, in _complete
    return completion.complete()
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 149, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 266, in _complete_python
    cached_name, n = self._complete_trailer(dot.get_previous_leaf())
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 345, in _complete_trailer
    values = infer_call_of_leaf(inferred_context, previous_leaf)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/helpers.py", line 81, in infer_call_of_leaf
    return context.infer_node(leaf)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/context.py", line 216, in infer_node
    return infer_node(self, node)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 165, in _infer_node
    return infer_atom(context, element)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 290, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/context.py", line 75, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/context.py", line 75, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/names.py", line 282, in infer
    self.tree_name
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/plugins/stdlib.py", line 825, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 719, in tree_name_to_values
    types = imports.infer_import(context, tree_name)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 54, in infer_import
    _prepare_infer_import(module_context, tree_name)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 117, in _prepare_infer_import
    return from_import_name, tuple(import_path), import_node.level, importer.follow()
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 259, in follow
    self._inference_state, self.import_path, sys_path, self._module_context
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 354, in import_module_by_names
    ) for parent_module_value in value_set
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 354, in <listcomp>
    ) for parent_module_value in value_set
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/plugins/flask.py", line 20, in wrapper
    return callback(inference_state, import_names, module_context, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/gradual/typeshed.py", line 115, in wrapper
    for p in parent_module_values
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/gradual/typeshed.py", line 115, in <genexpr>
    for p in parent_module_values
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 427, in import_module
    is_package=is_pkg,
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 443, in _load_python_module
    cache_path=settings.cache_directory
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/__init__.py", line 198, in parse
    return self.parse_and_get_code(*args, **kwargs)[0]
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/__init__.py", line 195, in parse_and_get_code
    return grammar.parse(code=code, path=path, file_io=file_io, **kwargs), code
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/grammar.py", line 78, in parse
    return self._parse(code=code, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/grammar.py", line 105, in _parse
    module_node = load_module(self._hashed, file_io, cache_path=cache_path)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 115, in load_module
    cache_path=cache_path
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 120, in _load_from_file_system
    cache_path = _get_hashed_path(hashed_grammar, path, cache_path=cache_path)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 190, in _get_hashed_path
    directory = _get_cache_directory_path(cache_path=cache_path)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 201, in _get_cache_directory_path
    os.makedirs(directory)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/zhfu/.cache/jedi/CPython-36-33'

Traceback (most recent call last):
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 106, in load_module
    module_cache_item = parser_cache[hashed_grammar][file_io.path]
KeyError: '/usr/lib/python3.6/os.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 307, in completions
    completions = script.completions()
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 214, in completions
    return self.complete(*self._pos, fuzzy=fuzzy)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/helpers.py", line 456, in wrapper
    return func(self, line, column, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 202, in complete
    return self._complete(line, column, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 210, in _complete
    return completion.complete()
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 149, in complete
    cached_name, completion_names = self._complete_python(leaf)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 266, in _complete_python
    cached_name, n = self._complete_trailer(dot.get_previous_leaf())
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/completion.py", line 345, in _complete_trailer
    values = infer_call_of_leaf(inferred_context, previous_leaf)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/helpers.py", line 81, in infer_call_of_leaf
    return context.infer_node(leaf)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/context.py", line 216, in infer_node
    return infer_node(self, node)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 137, in infer_node
    return _infer_node_if_inferred(context, element)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 150, in _infer_node_if_inferred
    return _infer_node_cached(context, element)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 155, in _infer_node_cached
    return _infer_node(context, element)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/debug.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 63, in wrapper
    return func(context, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 165, in _infer_node
    return infer_atom(context, element)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 290, in infer_atom
    return context.py__getattribute__(atom, position=position)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/context.py", line 75, in py__getattribute__
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/context.py", line 75, in <genexpr>
    values = ValueSet.from_sets(name.infer() for name in names)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/names.py", line 282, in infer
    self.tree_name
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/plugins/stdlib.py", line 825, in wrapper
    return func(inference_state, context, tree_name)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/syntax_tree.py", line 719, in tree_name_to_values
    types = imports.infer_import(context, tree_name)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/cache.py", line 43, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 54, in infer_import
    _prepare_infer_import(module_context, tree_name)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 117, in _prepare_infer_import
    return from_import_name, tuple(import_path), import_node.level, importer.follow()
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 259, in follow
    self._inference_state, self.import_path, sys_path, self._module_context
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 354, in import_module_by_names
    ) for parent_module_value in value_set
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 354, in <listcomp>
    ) for parent_module_value in value_set
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/plugins/__init__.py", line 21, in wrapper
    return built_functions[public_name](*args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/plugins/flask.py", line 20, in wrapper
    return callback(inference_state, import_names, module_context, *args, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/gradual/typeshed.py", line 115, in wrapper
    for p in parent_module_values
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/common/value.py", line 32, in from_sets
    for set_ in sets:
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/gradual/typeshed.py", line 115, in <genexpr>
    for p in parent_module_values
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 427, in import_module
    is_package=is_pkg,
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 443, in _load_python_module
    cache_path=settings.cache_directory
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/__init__.py", line 198, in parse
    return self.parse_and_get_code(*args, **kwargs)[0]
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/jedi/jedi/inference/__init__.py", line 195, in parse_and_get_code
    return grammar.parse(code=code, path=path, file_io=file_io, **kwargs), code
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/grammar.py", line 78, in parse
    return self._parse(code=code, **kwargs)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/grammar.py", line 105, in _parse
    module_node = load_module(self._hashed, file_io, cache_path=cache_path)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 115, in load_module
    cache_path=cache_path
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 120, in _load_from_file_system
    cache_path = _get_hashed_path(hashed_grammar, path, cache_path=cache_path)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 190, in _get_hashed_path
    directory = _get_cache_directory_path(cache_path=cache_path)
  File "/home/zhfu/.vim/bundle/jedi-vim/pythonx/parso/parso/cache.py", line 201, in _get_cache_directory_path
    os.makedirs(directory)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/zhfu/.cache/jedi/CPython-36-33'


1 line less; before #1  11 seconds ago
```

<details><summary>:scriptnames</summary>

```
  1: ~/.vim/bundle/jedi-vim/minimal.vimrc
  2: /usr/local/share/vim/vim82/syntax/syntax.vim
  3: /usr/local/share/vim/vim82/syntax/synload.vim
  4: /usr/local/share/vim/vim82/syntax/syncolor.vim
  5: /usr/local/share/vim/vim82/filetype.vim
  6: /usr/local/share/vim/vim82/ftplugin.vim
  7: /usr/local/share/vim/vim82/indent.vim
  8: /usr/local/share/vim/vim82/plugin/getscriptPlugin.vim
  9: /usr/local/share/vim/vim82/plugin/gzip.vim
 10: /usr/local/share/vim/vim82/plugin/logiPat.vim
 11: /usr/local/share/vim/vim82/plugin/manpager.vim
 12: /usr/local/share/vim/vim82/plugin/matchparen.vim
 13: /usr/local/share/vim/vim82/plugin/netrwPlugin.vim
 14: /usr/local/share/vim/vim82/plugin/rrhelper.vim
 15: /usr/local/share/vim/vim82/plugin/spellfile.vim
 16: /usr/local/share/vim/vim82/plugin/tarPlugin.vim
 17: /usr/local/share/vim/vim82/plugin/tohtml.vim
 18: /usr/local/share/vim/vim82/plugin/vimballPlugin.vim
 19: /usr/local/share/vim/vim82/plugin/zipPlugin.vim
 20: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 21: /usr/local/share/vim/vim82/syntax/python.vim
 22: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 23: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 24: /usr/local/share/vim/vim82/ftplugin/python.vim
 25: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 26: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 27: /usr/local/share/vim/vim82/indent/python.vim
```
</details>

**Comment by davidhalter** [comment]
This is parso trying to create its cache. Is there a reason you are not allowed to `/home/zhfu`?

**Comment by fuzhen011** [comment]
Ah, I just checked the directory and found the jedi folder inside it was owned by root account. I changed it to own by the user and now it works, thanks.

**Comment by davidhalter** [comment]
I'm closing. I don't think that it is to be expected that one cannot write to `~/.cache`.
