### ISSUE TITLE
Update to Jedi v0.17.2 breaks plugin

### ISSUE THREAD

**Issue by MaxG87** [davidhalter/jedi-vim#1033]
### Issue
I use jedi-vim through VimPlug. Today I ran `:PlugUpdate`, meaning effectively that I switched to revision a17b0333031bd3652ad4c6169caaed05ffb7c49d.

I used the proposed `minimal.vimrc` with `vim -u minimal.vimrc`. I then opened a file by `:e /path/to/file.py`. I give the output of `JediDebugInfo` below.

Switching to `a0207fadf9f165adac61f01abc07db0ae898cbe6`, the revision directly preceding a17b03, let the problem disappear.

##### jedi-vim version

 - jedi-vim git version: 0.10.0-38-ga17b033
 - jedi git submodule status:  3b7106ae71cb7bd3431101d169a0110ee0c179aa pythonx/jedi (v0.17.2)
 - parso git submodule status:  c864ca60d1a2f36524a4f79013a7de223e65e19d pythonx/parso (v0.6.0)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/home/mgoerner/.miniconda3/bin/python3`
 - global sys.version: `3.8.5 (default, Jul 28 2020, 12:59:40), [GCC 9.3.0]`
 - global site module: `/home/mgoerner/.miniconda3/lib/python3.8/site.py`
ERROR: could not import the "jedi" Python module: ImportError: bad magic number in 'jedi.common': b'\x03\xf3\r\n'
  Traceback (most recent call last):
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 114, in <module>
      import jedi
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py", line 32, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 24, in <module>
      from jedi.api import classes
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 24, in <module>
      from jedi.inference.utils import unite
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/__init__.py", line 70, in <module>
      from jedi.inference import imports
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 24, in <module>
      from jedi.inference import sys_path
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/sys_path.py", line 8, in <module>
      from jedi.common import traverse_parents

##### Settings

```
  omnifunc=python3complete#Complete
	Zuletzt gesetzt in /usr/share/vim/vim81/ftplugin/python.vim Zeile 41
  completeopt=menuone,longest,preview
	Zuletzt gesetzt in ~/.vim/plugged/jedi-vim/plugin/jedi.vim Zeile 36
```

#### :version
```

VIM - Vi IMproved 8.1 (2018 May 18 kompiliert am Apr 15 2020 06:40:31)
Inklusive der Patches: 1-2269
Verändert von team+vim@tracker.debian.org
Übersetzt von team+vim@tracker.debian.org
Riesige Version mit GTK3 GUI. Ein- (+) oder ausschließlich (-) der Eigenschaften:
+acl               +channel           +cscope            +ex_extra          -hangul_input      +lispindent        +mouse_gpm         +netbeans_intg     +python3           +startuptime       +terminfo          +virtualedit       -xfontset
+arabic            +cindent           +cursorbind        +extra_search      +iconv             +listcmds          -mouse_jsbterm     +num64             +quickfix          +statusline        +termresponse      +visual            +xim
+autocmd           +clientserver      +cursorshape       -farsi             +insert_expand     +localmap          +mouse_netterm     +packages          +reltime           -sun_workshop      +textobjects       +visualextra       +xpm
+autochdir         +clipboard         +dialog_con_gui    +file_in_path      +job               +lua               +mouse_sgr         +path_extra        +rightleft         +syntax            +textprop          +viminfo           +xsmp_interact
-autoservername    +cmdline_compl     +diff              +find_in_path      +jumplist          +menu              -mouse_sysmouse    +perl              -ruby              +tag_binary        +timers            +vreplace          +xterm_clipboard
+balloon_eval      +cmdline_hist      +digraphs          +float             +keymap            +mksession         +mouse_urxvt       +persistent_undo   +scrollbind        -tag_old_static    +title             +wildignore        -xterm_save
+balloon_eval_term +cmdline_info      +dnd               +folding           +lambda            +modify_fname      +mouse_xterm       +postscript        +signs             -tag_any_white     +toolbar           +wildmenu          
+browse            +comments          -ebcdic            -footer            +langmap           +mouse             +multi_byte        +printer           +smartindent       +tcl               +user_commands     +windows           
++builtin_terms    +conceal           +emacs_tags        +fork()            +libcall           +mouseshape        +multi_lang        +profile           +sound             +termguicolors     +vartabs           +writebackup       
+byte_offset       +cryptv            +eval              +gettext           +linebreak         +mouse_dec         -mzscheme          -python            +spell             +terminal          +vertsplit         +X11               
          System-vimrc-Datei: "$VIM/vimrc"
        Benutzer-vimrc-Datei: "$HOME/.vimrc"
 zweite Benutzer-vimrc-Datei: "~/.vim/vimrc"
         Benutzer-exrc-Datei: "$HOME/.exrc"
         System-gvimrc-Datei: "$VIM/gvimrc"
       Benutzer-gvimrc-Datei: "$HOME/.gvimrc"
zweite Benutzer-gvimrc-Datei: "~/.vim/gvimrc"
      defaults Datei: "$VIMRUNTIME/defaults.vim"
           System-Menü-Datei: "$VIMRUNTIME/menu.vim"
     Voreinstellung für $VIM: "/usr/share/vim"
Übersetzt: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-iU6mZD/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linken: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm     
```

#### :messages
```
Übersetzt von Christian Brabandt <cb@256bit.org>
"~/CodeUndDaten/symbology-api/config.py" 54L, 1429C
jedi-vim error: jedi#setup_python_imports: ImportError: bad magic number in 'jedi.common': b'\x03\xf3\r\n'
  Traceback (most recent call last):
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 114, in <module>
      import jedi
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py", line 32, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 24, in <module>
      from jedi.api import classes
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/classes.py", line 24, in <module>
      from jedi.inference.utils import unite
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/__init__.py", line 70, in <module>
      from jedi.inference import imports
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/imports.py", line 24, in <module>
      from jedi.inference import sys_path
    File "/home/mgoerner/.vim/plugged/jedi-vim/pythonx/jedi/jedi/inference/sys_path.py", line 8, in <module>
      from jedi.common import traverse_parents
Fehler beim Ausführen von "function jedi#init_python[11]..<SNR>23_display_exception":
Zeile   19:
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: bad magic number in 'jedi.common': b'\x03\xf3\r\n' (in function jedi#init_python[4]..<SNR>23_init_python[27]..jedi#setup_python_imports, Zeile 32). See :messages and/or :JediDebugInfo for more information.
```

<details><summary>:scriptnames</summary>

```
  1: ~/.vim/plugged/jedi-vim/minimal.vimrc
  2: /usr/share/vim/vim81/syntax/syntax.vim
  3: /usr/share/vim/vim81/syntax/synload.vim
  4: /usr/share/vim/vim81/syntax/syncolor.vim
  5: /usr/share/vim/vim81/filetype.vim
  6: /usr/share/vim/vim81/ftplugin.vim
  7: /usr/share/vim/vim81/indent.vim
  8: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
  9: /usr/share/vim/vim81/plugin/gzip.vim
 10: /usr/share/vim/vim81/plugin/logiPat.vim
 11: /usr/share/vim/vim81/plugin/manpager.vim
 12: /usr/share/vim/vim81/plugin/matchparen.vim
 13: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 14: /usr/share/vim/vim81/plugin/rrhelper.vim
 15: /usr/share/vim/vim81/plugin/spellfile.vim
 16: /usr/share/vim/vim81/plugin/tarPlugin.vim
 17: /usr/share/vim/vim81/plugin/tohtml.vim
 18: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 19: /usr/share/vim/vim81/plugin/zipPlugin.vim
 20: ~/.vim/plugged/jedi-vim/plugin/jedi.vim
 21: /usr/share/vim/vim81/syntax/python.vim
 22: ~/.vim/plugged/jedi-vim/after/syntax/python.vim
 23: ~/.vim/plugged/jedi-vim/autoload/jedi.vim
 24: /usr/share/vim/vim81/ftplugin/python.vim
 25: ~/.vim/plugged/jedi-vim/ftplugin/python/jedi.vim
 26: ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 27: /usr/share/vim/vim81/indent/python.vim
```
</details>

**Comment by blueyed** [comment]
Try removing `.pyc` files (i.e. `__pycache__` folders).

**Comment by davidhalter** [comment]
Yes, 99% this is that issue again. Or reinstall jedi-vim/Jedi.

**Comment by MaxG87** [comment]
Removing `.pyc` and `__pycache__` did not help. Reinstalling did.

I `rm -rf ~/.vim/plugged/jedi-vim` and installed the package back using `:PlugInstall`. No opening files works again.
