### ISSUE TITLE
startup fails in v0.11.0 (works fine in v0.10.0)

### ISSUE THREAD

**Issue by MironVeryanskiy** [davidhalter/jedi-vim#1043]
### Issue

Unable to launch jedi-vim using git tag v0.11.0, but having no issues launching with git tag v0.10.0

### Steps to reproduce

Using the template `minimal.vimrc`:
```
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

" Put your config changes here.
" let g:jedi#show_call_signatures=1

syntax on
filetype plugin indent on
```

Launch vim into a python file: `vim -u minimal.vimrc newfile.py `

##### jedi-vim version

 - jedi-vim git version: 0.11.0
 - jedi git submodule status:  4b5b2e791b66f3a99542bc2a0e1d5730dc1491df pythonx/jedi (v0.18.0)
 - parso git submodule status:  ef90bba3b3d4310c345885a1368dbfc8937765a3 pythonx/parso (v0.8.1-1-gef90bba)

##### Global Python

Using Python version 3 to access Jedi.
Error when running display_debug_info: Vim(python3):Traceback (most recent call last):

##### Settings

```
  omnifunc=pythoncomplete#Complete
        Last set from /usr/share/vim/vim74/ftplugin/python.vim
  completeopt=menuone,longest,preview
        Last set from ~/.vim/plugged/jedi-vim/plugin/jedi.vim
```

#### :version
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 18 2020 14:06:17)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl             ++builtin_terms  -clipboard       +conceal         +dialog_con      +emacs_tags      +file_in_path    +fork()          +job             +linebreak       +menu            +mouse_dec       -mouse_sysmouse  -mzscheme        +persistent_undo +python3         +scrollbind      -sun_workshop    +tcl             +title           +visual          +wildmenu        -xim
+arabic          +byte_offset     +cmdline_compl   +cryptv          +diff            +eval            +find_in_path    +gettext         +jumplist        +lispindent      +mksession       +mouse_gpm       +mouse_urxvt     +netbeans_intg   +postscript      +quickfix        +signs           +syntax          +terminfo        -toolbar         +visualextra     +windows         -xsmp
+autocmd         +channel         +cmdline_hist    +cscope          +digraphs        +ex_extra        +float           -hangul_input    +keymap          +listcmds        +modify_fname    -mouse_jsbterm   +mouse_xterm     +packages        +printer         +reltime         +smartindent     +tag_binary      +termresponse    +user_commands   +viminfo         +writebackup     -xterm_clipboard
-balloon_eval    +cindent         +cmdline_info    +cursorbind      -dnd             +extra_search    +folding         +iconv           +langmap         +localmap        +mouse           +mouse_netterm   +multi_byte      +path_extra      +profile         +rightleft       +startuptime     +tag_old_static  +textobjects     +vertsplit       +vreplace        -X11             -xterm_save
-browse          -clientserver    +comments        +cursorshape     -ebcdic          +farsi           -footer          +insert_expand   +libcall         +lua             -mouseshape      +mouse_sgr       +multi_lang      +perl            -python          +ruby            +statusline      -tag_any_white   +timers          +virtualedit     +wildignore      -xfontset        -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm
 -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
jedi-vim error: jedi#setup_python_imports: Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1139, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1115, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1093, in _legacy_get_spec
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "/home/miron/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 114, in <module>
    import jedi
  File "/home/miron/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py", line 32, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, preload_module
  File "/home/miron/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 13, in <module>
    import parso
  File "/home/miron/.vim/plugged/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/miron/.vim/plugged/jedi-vim/pythonx/parso/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax
Error detected while processing function jedi#init_python[11]..<SNR>22_display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: Traceback (most recent call last): (in function jedi#init_python[4]..<SNR>22_init_python[6]..jedi#setup_python_imports, line 20). See :messages and/or :JediDebugInfo for more information.
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 18 2020 14:06:17)
  1: ~/.vim/plugged/jedi-vim/minimal.vimrc
  2: /usr/share/vim/vim74/syntax/syntax.vim
  3: /usr/share/vim/vim74/syntax/synload.vim
  4: /usr/share/vim/vim74/syntax/syncolor.vim
  5: /usr/share/vim/vim74/filetype.vim
  6: /usr/share/vim/vim74/ftplugin.vim
  7: /usr/share/vim/vim74/indent.vim
  8: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
  9: /usr/share/vim/vim74/plugin/gzip.vim
 10: /usr/share/vim/vim74/plugin/logiPat.vim
 11: /usr/share/vim/vim74/plugin/matchparen.vim
 12: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 13: /usr/share/vim/vim74/plugin/rrhelper.vim
 14: /usr/share/vim/vim74/plugin/spellfile.vim
 15: /usr/share/vim/vim74/plugin/tarPlugin.vim
 16: /usr/share/vim/vim74/plugin/tohtml.vim
 17: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 18: /usr/share/vim/vim74/plugin/zipPlugin.vim
 19: ~/.vim/plugged/jedi-vim/plugin/jedi.vim
 20: /usr/share/vim/vim74/syntax/python.vim
 21: ~/.vim/plugged/jedi-vim/after/syntax/python.vim
 22: ~/.vim/plugged/jedi-vim/autoload/jedi.vim
 23: /usr/share/vim/vim74/ftplugin/python.vim
 24: ~/.vim/plugged/jedi-vim/ftplugin/python/jedi.vim
 25: ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 26: /usr/share/vim/vim74/indent/python.vim
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 18 2020 14:06:17)
  1: ~/.vim/plugged/jedi-vim/minimal.vimrc
  2: /usr/share/vim/vim74/syntax/syntax.vim
  3: /usr/share/vim/vim74/syntax/synload.vim
  4: /usr/share/vim/vim74/syntax/syncolor.vim
  5: /usr/share/vim/vim74/filetype.vim
  6: /usr/share/vim/vim74/ftplugin.vim
  7: /usr/share/vim/vim74/indent.vim
  8: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
  9: /usr/share/vim/vim74/plugin/gzip.vim
 10: /usr/share/vim/vim74/plugin/logiPat.vim
 11: /usr/share/vim/vim74/plugin/matchparen.vim
 12: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 13: /usr/share/vim/vim74/plugin/rrhelper.vim
 14: /usr/share/vim/vim74/plugin/spellfile.vim
 15: /usr/share/vim/vim74/plugin/tarPlugin.vim
 16: /usr/share/vim/vim74/plugin/tohtml.vim
 17: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 18: /usr/share/vim/vim74/plugin/zipPlugin.vim
 19: ~/.vim/plugged/jedi-vim/plugin/jedi.vim
 20: /usr/share/vim/vim74/syntax/python.vim
 21: ~/.vim/plugged/jedi-vim/after/syntax/python.vim
 22: ~/.vim/plugged/jedi-vim/autoload/jedi.vim
 23: /usr/share/vim/vim74/ftplugin/python.vim
 24: ~/.vim/plugged/jedi-vim/ftplugin/python/jedi.vim
 25: ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 26: /usr/share/vim/vim74/indent/python.vim
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 18 2020 14:06:17)
  1: ~/.vim/plugged/jedi-vim/minimal.vimrc
  2: /usr/share/vim/vim74/syntax/syntax.vim
  3: /usr/share/vim/vim74/syntax/synload.vim
  4: /usr/share/vim/vim74/syntax/syncolor.vim
  5: /usr/share/vim/vim74/filetype.vim
  6: /usr/share/vim/vim74/ftplugin.vim
  7: /usr/share/vim/vim74/indent.vim
  8: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
  9: /usr/share/vim/vim74/plugin/gzip.vim
 10: /usr/share/vim/vim74/plugin/logiPat.vim
 11: /usr/share/vim/vim74/plugin/matchparen.vim
 12: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 13: /usr/share/vim/vim74/plugin/rrhelper.vim
 14: /usr/share/vim/vim74/plugin/spellfile.vim
 15: /usr/share/vim/vim74/plugin/tarPlugin.vim
 16: /usr/share/vim/vim74/plugin/tohtml.vim
 17: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 18: /usr/share/vim/vim74/plugin/zipPlugin.vim
 19: ~/.vim/plugged/jedi-vim/plugin/jedi.vim
 20: /usr/share/vim/vim74/syntax/python.vim
 21: ~/.vim/plugged/jedi-vim/after/syntax/python.vim
 22: ~/.vim/plugged/jedi-vim/autoload/jedi.vim
 23: /usr/share/vim/vim74/ftplugin/python.vim
 24: ~/.vim/plugged/jedi-vim/ftplugin/python/jedi.vim
 25: ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 26: /usr/share/vim/vim74/indent/python.vim
 27: /usr/share/vim/vim74/syntax/vim.vim
 28: /usr/share/vim/vim74/syntax/lua.vim
 29: /usr/share/vim/vim74/syntax/perl.vim
 30: /usr/share/vim/vim74/syntax/pod.vim
 31: /usr/share/vim/vim74/syntax/ruby.vim
 32: /usr/share/vim/vim74/ftplugin/vim.vim
33: /usr/share/vim/vim74/indent/vim.vim
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 18 2020 14:06:17)
```

<details><summary>:scriptnames</summary>

```
  1: ~/.vim/plugged/jedi-vim/minimal.vimrc
  2: /usr/share/vim/vim74/syntax/syntax.vim
  3: /usr/share/vim/vim74/syntax/synload.vim
  4: /usr/share/vim/vim74/syntax/syncolor.vim
  5: /usr/share/vim/vim74/filetype.vim
  6: /usr/share/vim/vim74/ftplugin.vim
  7: /usr/share/vim/vim74/indent.vim
  8: /usr/share/vim/vim74/plugin/getscriptPlugin.vim
  9: /usr/share/vim/vim74/plugin/gzip.vim
 10: /usr/share/vim/vim74/plugin/logiPat.vim
 11: /usr/share/vim/vim74/plugin/matchparen.vim
 12: /usr/share/vim/vim74/plugin/netrwPlugin.vim
 13: /usr/share/vim/vim74/plugin/rrhelper.vim
 14: /usr/share/vim/vim74/plugin/spellfile.vim
 15: /usr/share/vim/vim74/plugin/tarPlugin.vim
 16: /usr/share/vim/vim74/plugin/tohtml.vim
 17: /usr/share/vim/vim74/plugin/vimballPlugin.vim
 18: /usr/share/vim/vim74/plugin/zipPlugin.vim
 19: ~/.vim/plugged/jedi-vim/plugin/jedi.vim
 20: /usr/share/vim/vim74/syntax/python.vim
 21: ~/.vim/plugged/jedi-vim/after/syntax/python.vim
 22: ~/.vim/plugged/jedi-vim/autoload/jedi.vim
 23: /usr/share/vim/vim74/ftplugin/python.vim
 24: ~/.vim/plugged/jedi-vim/ftplugin/python/jedi.vim
 25: ~/.vim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 26: /usr/share/vim/vim74/indent/python.vim
 27: /usr/share/vim/vim74/syntax/vim.vim
 28: /usr/share/vim/vim74/syntax/lua.vim
 29: /usr/share/vim/vim74/syntax/perl.vim
 30: /usr/share/vim/vim74/syntax/pod.vim
 31: /usr/share/vim/vim74/syntax/ruby.vim
 32: /usr/share/vim/vim74/ftplugin/vim.vim
 33: /usr/share/vim/vim74/indent/vim.vim
```
</details>

**Comment by davidhalter** [comment]
Python 3.5 is no longer supported.
