### ISSUE TITLE
ValueError: invalid \x escape

### ISSUE THREAD

**Issue by benbarbour** [davidhalter/jedi-vim#248]
Hello,

I'm seeing this traceback periodically when I run :messages in vim. I haven't been able to determine exactly what triggers it yet, but I am seeing some odd behaviors with jedi-vim. Like, renaming a variable opens a new tab and both tabs lose their syntax highlighting, some odd indentation choices (but that might just be vim).

```
Traceback (most recent call last):
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi_vim.py", line 19, in wrapper
    return func(*args, **kwargs)
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi_vim.py", line 248, in show_call_signatures
    signatures = get_script().call_signatures()
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi/jedi/api_classes.py", line 44, in wrapper
    result = func(*args, **kwds)
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi/jedi/api.py", line 500, in call_signatures
    call, index = self._func_call_and_param_index()
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi/jedi/api.py", line 520, in _func_call_and_param_index
    user_stmt, self._pos)
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi/jedi/helpers.py", line 120, in search_function_definition
    arr, index = array_for_pos(stmt, pos, [pr.Array.TUPLE, pr.Array.NOARRAY])
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi/jedi/helpers.py", line 103, in array_for_pos
    for command in stmt.get_commands():
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi/jedi/parsing_representation.py", line 848, in get_commands
    result = self._parse_statement()
  File "/home/bbarbour/.bbenv/vim/bundle/jedi-vim/jedi/jedi/parsing_representation.py", line 1065, in _parse_statement
    tok = literal_eval(tok)
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
ValueError: invalid \x escape
```

**Comment by davidhalter** [comment]
Since I have fixed at least two related issues, I believe this one is fixed. Let me know if you're still seeing it (latest Jedi dev branch).

Also the above traceback cannot even occur anymore, because most of those functions don't exist anymore. (Actually all, except the first API call!)
