### ISSUE TITLE
Errors on CursorMovedI when jedi_vim is not installed

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi-vim#263]
When using the plugin on a machine where jedi_vim is not installed (e.g. via a dotfiles repo), the CursorMovedI autocommands get setup anyway, which results in very annoying tracebacks while editing:

    Error detected while processing CursorMovedI Auto commands for "<buffer=6>":
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    NameError: name 'jedi_vim' is not defined

While at it, the initial error during startup could be less verbose or friendlier.

My workaround is to disable the bundle on this machine, but that makes the configs divert.

**Comment by itchyny** [comment]
I've encountered this problem. This plugin causes annoying error message on environment without jedi. I share my configuration on multiple PCs and some have jedi installed and others do not.
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing /path/to/jedi/autoload/jedi.vim:
line  347:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/path/to/jedi/initialize.py", line 24, in <module>
    vim.command('echoerr "Please install Jedi if you want to use jedi_vim."')
vim.error: Vim(echoerr):Please install Jedi if you want to use jedi_vim.
E171: Missing :endif
Error detected while processing /path/to/jedi/ftplugin/python/jedi.vim:
line    8:
E121: Undefined variable: g:jedi#auto_initialization
E171: Missing :endif
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
Traceback (most recent call last):
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
  File "<string>", line 1, in <module>
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
NameError: name 'jedi_vim' is not defined
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
Traceback (most recent call last):
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
  File "<string>", line 1, in <module>
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
NameError: name 'jedi_vim' is not defined
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
Traceback (most recent call last):
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
  File "<string>", line 1, in <module>
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
NameError: name 'jedi_vim' is not defined
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
Traceback (most recent call last):
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
  File "<string>", line 1, in <module>
Error detected while processing CursorMovedI Auto commands for "<buffer=1>":
NameError: name 'jedi_vim' is not defined
Error detected while processing InsertLeave Auto commands for "<buffer=1>":
Traceback (most recent call last):
Error detected while processing InsertLeave Auto commands for "<buffer=1>":
  File "<string>", line 1, in <module>
Error detected while processing InsertLeave Auto commands for "<buffer=1>":
NameError: name 'jedi_vim' is not defined
```

**Comment by davidhalter** [comment]
Confirmed.

**Comment by blueyed** [comment]
@davidhalter 
Thanks for addressing this!
