### ISSUE TITLE
jedi-vim can't complete for python's socket library

### ISSUE THREAD

**Issue by ffledgling** [davidhalter/jedi-vim#264]
I installed jedi-vim as recommended.

I can use C-Space to autocomplete for most python libraries, math, random, string, matplotlib etc. But I can't get it to work for socket.
I have vim 7.4

Output of `vim --version`

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 15 2014 12:09:00)
Included patches: 1-179
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
-balloon_eval    +float           +mouse_urxvt     -tag_any_white
-browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
-clientserver    -hangul_input    +netbeans_intg   +title
-clipboard       +iconv           +path_extra      -toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
+emacs_tags      -mouseshape      -sniff           -xsmp
+eval            +mouse_dec       +startuptime     -xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim74"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -g -pipe -Wall -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1      
Linking: gcc   -L. -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags  -Wl,-z,relro  -L/usr/local/lib -Wl,--as-needed -o vim        -lm -lnsl  -lselinux  -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc       
```

I simply see a `Omni completion (^O^N^P) Pattern not found` when I hit `<C-Space>` after `socket.`

The only other plugins I have are: colorscheme and powerline.

Output of `:messages` in vim shows:

```
Traceback (most recent call last):
  File "/home/anhad/.vim/bundle/jedi-vim/jedi_vim.py", line 121, in completions
    completions = script.completions()
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/api_classes.py", line 44, in wrapper
    result = func(*args, **kwds)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/api.py", line 124, in completions
    completions = get_completions(user_stmt, bs)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/api.py", line 114, in get_completions
    return self._simple_complete(path, like)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/api.py", line 164, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/api.py", line 229, in _prepare_goto
    scopes = evaluate.follow_statement(stmt)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/recursion.py", line 31, in __call__
    result = self.func(stmt, *args, **kwargs)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 101, in wrapper
    rv = function(*args, **kwargs)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/evaluate.py", line 611, in follow_statement
    result = follow_call_list(commands)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/common.py", line 56, in wrapper
    return func(*args, **kwds)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/evaluate.py", line 682, in follow_call_list
    result += follow_call(call)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/evaluate.py", line 700, in follow_call
    return follow_call_path(path, s.parent, s.start_pos)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/evaluate.py", line 723, in follow_call_path
    result = imports.strip_imports(scopes)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/imports.py", line 390, in strip_imports
    result += ImportPath(s).follow()
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/imports.py", line 213, in follow
    scopes += remove_star_imports(scope)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 158, in wrapper
    mods = func(scope, *args, **kwargs)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/imports.py", line 404, in remove_star_imports
    modules = strip_imports(i for i in scope.get_imports() if i.star)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/imports.py", line 390, in strip_imports
    result += ImportPath(s).follow()
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/imports.py", line 206, in follow
    scope, rest = self._follow_file_system()
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/imports.py", line 379, in _follow_file_system
    return f.parser.module, rest
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/modules.py", line 48, in parser
    or self._load_module()
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/modules.py", line 55, in _load_module
    source = self._get_source()
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/builtin.py", line 124, in _get_source
    return _generate_code(self.module, self._load_mixins())
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/builtin.py", line 119, in module
    load_module(name, path)
  File "/home/anhad/.vim/bundle/jedi-vim/jedi/jedi/builtin.py", line 90, in load_module
    exec_function('import %s as module' % name, content)
  File "blub", line 2, in exec_function
  File "<string>", line 1, in <module>
ImportError: dynamic module does not define init function (init_socketmodule)
```

I talked to people over in #vim on freenode, I didn't find anyone who was able to reproduce it. If this is some setup problem on my end, please let me know, if this is a bug, could you please fix it?

**Comment by davidhalter** [comment]
Completion works definitely with the latest jedi master. I think it already worked in 0.10.0. socket completion support is marginal in Python2.7 but gets better in 3.
