### ISSUE TITLE
Popup a string "denepo_etelpmoc#idej=" when complete matplotlib and pylab.

### ISSUE THREAD

**Issue by abcat** [davidhalter/jedi-vim#274]
I installed jedi-vim using Vundle in Xubnutu 14.04 Vim7.4.
It can complete many libraries such as os urllib2 and numpy, but it does not complete matplotlib or pylab. And it auto pop up a string "denepo_etelpmoc#idej=".
After setting the popup_on_dot=0, I use <c-p> and find the error message:
```vim
简体中文消息维护者: Yuheng Xie <elephant@linux.net.cn>
"pythoncomplete.vim" [只读] 626L, 22047C
Traceback (most recent call last):
  File "/home/abcat/.vim/bundle/jedi-vim/jedi_vim.py", line 133, in completions
    menu=PythonToVimStr(c.description),
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/api/classes.py", line 449, in description
    t = self.type
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/api/classes.py", line 494, in type
    followed = self.follow_definition()
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/api/classes.py", line 526, in follow_definition
    defs = self._follow_statements_imports()
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/api/classes.py", line 511, in _follow_statements_imports
    i._importer.module).follow(self._evaluator)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 290, in follow
    return evaluator.follow_path(iter(rest), [scope], scope)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 248, in follow_path
    fp = self._follow_path(iter_paths[i], typ, call_scope)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 294, in _follow_path
    result = imports.strip_imports(self, types)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 427, in strip_imports
    result += ImportWrapper(evaluator, s).follow()
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 214, in follow
    for s in scopes))
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 214, in <genexpr>
    for s in scopes))
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 248, in follow_path
    fp = self._follow_path(iter_paths[i], typ, call_scope)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 293, in _follow_path
    types = self.find_types(typ, current)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 110, in find_types
    return f.find(scopes, resolve_decorator)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 38, in find
    types = self._names_to_types(names, resolve_decorator)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 182, in _names_to_types
    types += self._remove_statements(typ)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 217, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=unicode(self.name_str))
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 150, in eval_statement
    new_result += finder.find_assignments(ass_expression_list[0], result, seek_name)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 527, in find_assignments
    return _assign_tuples(lhs, results, seek_name)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 508, in _assign_tuples
    result += find_assignments(command, r, seek_name)
  File "/home/abcat/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 528, in find_assignments
    elif unicode(lhs.name.names[-1]) == seek_name:
AttributeError: 'Token' object has no attribute 'name'

E475: 无效的参数:(means:Invalid argument) 

```
omnifunc=jedi#completions

![output](https://cloud.githubusercontent.com/assets/5227944/3011699/bbed4d34-df2e-11e3-9981-d7cbd439cedd.gif)

My vimrc works fine in windows7 and windows xp, and the version of matplotlib is 1.3.1.

**Comment by davidhalter** [comment]
Alright. Completing pylab works now. It's still way to slow, but it works. Check the latest Jedi branch!
