### ISSUE TITLE
unable to open definition

### ISSUE THREAD

**Issue by raghuramos1987** [davidhalter/jedi-vim#304]
I started getting this error. AFAIK I havent changed any configurations and it was working fine till a few days back. I'm on ubuntu 11.10

Traceback (most recent call last):
  File "/home/raghu/.vim/bundle/jedi-vim/jedi_vim.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi_vim.py", line 160, in goto
    definitions = script.goto_definitions()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 393, in goto_definitions
    definitions = set(self._prepare_goto(goto_path))
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 265, in _prepare_goto
    scopes = self._evaluator.eval_statement(eval_stmt)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 51, in wrapper
    result = func(*args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 127, in eval_statement
    result = self.eval_expression_list(expression_list)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 162, in eval_expression_list
    return self.process_precedence_element(p) or []
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 172, in process_precedence_element
    return self._eval_statement_element(el)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 202, in _eval_statement_element
    return self.eval_call(element)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 214, in eval_call
    return self.eval_call_path(path, s.parent, s.start_pos)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 228, in eval_call_path
    search_global=True)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 110, in find_types
    return f.find(scopes, resolve_decorator)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 37, in find
    names = self.filter_name(scopes)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 63, in filter_name
    for nscope, name_list in scope_generator:
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 460, in get_names_of_scope
    for s in imports.remove_star_imports(evaluator, non_flow.get_parent_until()):
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 173, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 442, in remove_star_imports
    modules = strip_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 427, in strip_imports
    result += ImportWrapper(evaluator, s).follow()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 194, in follow
    scopes += remove_star_imports(self._evaluator, scope)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 173, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 442, in remove_star_imports
    modules = strip_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 427, in strip_imports
    result += ImportWrapper(evaluator, s).follow()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 194, in follow
    scopes += remove_star_imports(self._evaluator, scope)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 173, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 442, in remove_star_imports
    modules = strip_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 427, in strip_imports
    result += ImportWrapper(evaluator, s).follow()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 188, in follow
    scope, rest = self._importer.follow_file_system()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 313, in follow_file_system
    return self._follow_sys_path(sys_path_mod)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 414, in _follow_sys_path
    return load_module(path, source), rest
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 467, in load_module
    return load(source) if cached is None else cached.module
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 462, in load
    p = fast.FastParser(common.source_to_unicode(source), p)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 65, in __call__
    p = super(CachedFastParser, self).__call__(source, module_path)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 196, in __init__
    self._parse(code)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 313, in _parse
    line_offset, nodes, not is_first)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 374, in _get_parser
    top_module=self.module, no_docstr=no_docstr)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 59, in __init__
    self._parse()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 556, in _parse
    stmt, tok = self._parse_statement()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 290, in _parse_statement
    tok = next(self._gen)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 617, in next
    return self.__next__()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 624, in __next__
    self.current = next(self._tokenizer)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 412, in next
    return self.__next__()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 418, in __next__
  scopes += remove_star_imports(self._evaluator, scope)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 173, in wrapper
    mods = func(evaluator, scope, *args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 442, in remove_star_imports
    modules = strip_imports(evaluator, (i for i in scope.get_imports() if i.star))
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 427, in strip_imports
    result += ImportWrapper(evaluator, s).follow()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 188, in follow
    scope, rest = self._importer.follow_file_system()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 313, in follow_file_system
    return self._follow_sys_path(sys_path_mod)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 414, in _follow_sys_path
    return load_module(path, source), rest
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 467, in load_module
    return load(source) if cached is None else cached.module
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 462, in load
    p = fast.FastParser(common.source_to_unicode(source), p)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 65, in __call__
    p = super(CachedFastParser, self).__call__(source, module_path)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 196, in __init__
    self._parse(code)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 313, in _parse
    line_offset, nodes, not is_first)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 374, in _get_parser
    top_module=self.module, no_docstr=no_docstr)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 59, in __init__
    self._parse()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 556, in _parse
    stmt, tok = self._parse_statement()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 290, in _parse_statement
    tok = next(self._gen)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 617, in next
    return self.__next__()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 624, in __next__
    self.current = next(self._tokenizer)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 412, in next
    return self.__next__()
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 418, in __next__
    current = next(self.gen)
  File "/home/raghu/.vim/bundle/jedi-vim/jedi/jedi/parser/tokenize.py", line 285, in generate_tokens
    endprog = (endprogs[initial] or endprogs[token[1]] or
KeyError: u'u'

**Comment by davidhalter** [comment]
Latest Jedi dev branch fixes this.
