### ISSUE TITLE
KeyError: u'u' bug or...?

### ISSUE THREAD

**Issue by aliev** [davidhalter/jedi-vim#338]
when i type something like this completion stops working in the whole file:

```
print u'first\
second'
```

after pressing leader+d i get an error:

```
Traceback (most recent call last):
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi_vim.py", line 23, in wrapper
    return func(*args, **kwargs)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi_vim.py", line 160, in goto
    definitions = script.goto_definitions()
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 371, in goto_definitions
    user_stmt = self._parser.user_stmt_with_whitespace()
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 141, in wrapper
    result = func(self)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 227, in user_stmt_with_whitespace
    user_stmt = self.user_stmt()
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 141, in wrapper
    result = func(self)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 217, in user_stmt
    module = self.module()
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 256, in module
    return self._parser().module
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 141, in wrapper
    result = func(self)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 210, in _parser
    parser = FastParser(self._source, self._path)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 65, in __call__
    p = super(CachedFastParser, self).__call__(source, module_path)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 196, in __init__
    self._parse(code)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 313, in _parse
    line_offset, nodes, not is_first)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 374, in _get_parser
    top_module=self.module, no_docstr=no_docstr)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 59, in __init__
    self._parse()
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 594, in _parse
    stmt, tok = self._parse_statement(self._gen.current)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 342, in _parse_statement
    n, tok = self._parse_dot_name(self._gen.current)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 120, in _parse_dot_name
    tok = next(self._gen)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 617, in next
    return self.__next__()
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 624, in __next__
    self.current = next(self._tokenizer)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 412, in next
    return self.__next__()
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 418, in __next__
    current = next(self.gen)
  File "/Users/aliev/.vim/bundle/jedi-vim/jedi/jedi/parser/tokenize.py", line 285, in generate_tokens
    endprog = (endprogs[initial] or endprogs[token[1]] or
KeyError: u'u'
```

**Comment by davidhalter** [comment]
Seems to be working (latest Jedi dev tree).

**Comment by aliev** [comment]
@davidhalter cool!
