### ISSUE TITLE
crash when using find-uses (<Leader>-n)

### ISSUE THREAD

**Issue by assaflavie** [davidhalter/jedi-vim#381]
Using find-uses on the function name yields the following stack trace:
```
Traceback (most recent call last):
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi_vim.py", line 48, in wrapper
    return func(*args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi_vim.py", line 197, in goto
    definitions = script.usages()
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 480, in usages
    names = usages.usages(self._evaluator, definitions, module)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/api/usages.py", line 32, in usages
    result = evaluator.goto(name)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 352, in goto
    types = self.eval_element(call)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 172, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 242, in eval_trailer
    new_types += self.find_types(typ, node)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 105, in find_types
    return f.find(scopes, search_global)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 278, in _name_to_types
    types += _remove_statements(evaluator, typ, name)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 323, in _remove_statements
    types += evaluator.eval_statement(stmt, seek_name=name)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/recursion.py", line 24, in run
    result = func(evaluator, stmt, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 120, in eval_statement
    types = self.eval_element(stmt.get_rhs())
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 172, in eval_element
    types = self.eval_trailer(types, trailer)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 244, in eval_trailer
    new_types += self.execute(typ, node, trailer)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 284, in execute
    types = func(self, arguments)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/_compatibility.py", line 119, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/representation.py", line 555, in py__call__
    return FunctionExecution(evaluator, self, params).get_return_types()
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/recursion.py", line 102, in run
    result = func(execution, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/representation.py", line 618, in get_return_types
    check = flow_analysis.break_check(self._evaluator, self, r)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/flow_analysis.py", line 49, in break_check
    return _break_check(evaluator, stmt, base_scope, element_scope)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/flow_analysis.py", line 67, in _break_check
    reachable = _check_if(evaluator, node)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/flow_analysis.py", line 81, in _check_if
    types = evaluator.eval_element(node)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 197, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/precedence.py", line 43, in calculate_children
    types = evaluator.eval_element(next(iterator))
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 168, in eval_element
    types = self._eval_atom(element.children[0])
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 215, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 105, in find_types
    return f.find(scopes, search_global)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 90, in iter_content
    return f.get_return_types(check_yields=True)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/recursion.py", line 102, in run
    result = func(execution, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/representation.py", line 622, in get_return_types
    types += self._evaluator.eval_element(r.children[1])
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 154, in eval_element
    return self._eval_atom(element)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 215, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 105, in find_types
    return f.find(scopes, search_global)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 407, in get_iterator_types
    result += it.values()
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 236, in values
    result = unite(self._evaluator.eval_element(v) for v in self._values())
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 38, in unite
    return list(chain.from_iterable(iterable))
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 236, in <genexpr>
    result = unite(self._evaluator.eval_element(v) for v in self._values())
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 154, in eval_element
    return self._eval_atom(element)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 215, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 105, in find_types
    return f.find(scopes, search_global)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 269, in _name_to_types
    for_types = iterable.get_iterator_types(for_types)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 418, in get_iterator_types
    result += it.iter_content()
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 577, in iter_content
    items += _check_array_additions(self._evaluator, self.instance, module, is_list)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 483, in _check_array_additions
    comp_arr_parent = get_execution_parent(compare_array)
  File "/Users/assaf/.vim/bundle/jedi-vim/jedi/jedi/evaluate/iterable.py", line 477, in get_execution_parent
    return node.get_parent_until(er.FunctionExecution)
AttributeError: 'NoneType' object has no attribute 'get_parent_until'

```

Weird thing is that it does work on other member functions in the same class. Some work, some crash. hard to tell what the pattern behind these is, but it might be that functions that are used outside the file cause crashes, while functions whose only uses are within the same module work.

**Comment by davidhalter** [comment]
Would it be possible for you to post the source code as well as the position that you're using `<Leader>-n`?

**Comment by assaflavie** [comment]
I'm afraid that this source code is proprietary/commercial, so I'm not allowed to. Is there any other way I can help debug this?

**Comment by blueyed** [comment]
@assaflavie 
Can you extract / abstract a reproducible test case out of it?

Apart from that, please try the latest version of jedi-vim / jedi, which might have fixed this.
