### ISSUE TITLE
Missing error message (and full traceback) with v:exception

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi-vim#476]
I've noticed that `v:exception` which is uses during loading jedi-vim won't include the error itself, nor the full traceback.

    :try | exec 'py raise("foo")' | catch | echom v:exception | endtry
    Vim(python):Traceback (most recent call last):

With Neovim it's better:

    :try | exec 'py raise("foo")' | catch | echom v:exception | endtry
    Vim(return):TypeError('exceptions must be old-style classes or derived from BaseException, not str',)

**Comment by davidhalter** [comment]
And what is the idea of this issue? I don't get it.

**Comment by blueyed** [comment]
I don't have a solution for this yet, just wanted to leave it here for now.

I could imagine making use of the existing (Python) wrappers to set this information in some Vim variable.

The problem is that there's no real error in the case when loading jedi_vim fails.

**Comment by blueyed** [comment]
It would help with issues with https://github.com/davidhalter/jedi-vim/issues/447.

**Comment by tony** [comment]
@davidhalter 

Currently, errors are like this:

```
Vim(return):TypeError('exceptions must be old-style classes or derived from BaseException, not str',)
```

But there's no stacktrace / traceback, for example:

```python
Traceback (most recent call last):
  File "hi.py", line 10, in <module>
    myfunc('moo')
  File "hi.py", line 6, in myfunc
    moo = paths - myparam
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

If we had that information, bug reports could be much more helpful.

**Comment by blueyed** [comment]
See also https://github.com/davidhalter/jedi-vim/issues/592, where we did not get a report/message from an error in Jedi.
