### ISSUE TITLE
jedi#goto_command gives traceback in python3

### ISSUE THREAD

**Issue by MiguelLatorre** [davidhalter/jedi-vim#478]
Reason:
python3 has no string.lowercase

Traceback (most recent call last):
  File "/home/mal/.vim/bundle/vim-jedi/jedi_vim.py", line 115, in wrapper
    return func(*args, **kwargs)
  File "/home/mal/.vim/bundle/vim-jedi/jedi_vim.py", line 258, in goto
    for _ in range(4)])
  File "/home/mal/.vim/bundle/vim-jedi/jedi_vim.py", line 258, in <listcomp>
    for _ in range(4)])
AttributeError: module 'string' has no attribute 'lowercase'

**Comment by blueyed** [comment]
Thanks for the report.

It does not exist for Python 2 either.  A fix is available in https://github.com/davidhalter/jedi-vim/pull/480.
