### ISSUE TITLE
Specific list comprehension blows up jedi

### ISSUE THREAD

**Issue by omikronsc** [davidhalter/jedi-vim#488]
Hi!

First of all, thanks for this extension!

I found that specific list comphenesion blows up jedi and make impossible to use code completion if this is in file:

```python
class Foo(object):                                                              
    def __init__(self, first):                                                  
        print(first)                                                            
                                                                                
items = [[1,2,3,4], [4,5,6,7]]                                                  
                                                                                
test = [Foo(first) for first, *rest in items]  
```

Effect is that trying to jump to definition of Foo from assignment statement causes completely incomprehensible traceback:
```
Traceback (most recent call last):
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi_vim.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi_vim.py", line 228, in goto
    definitions = script.goto_assignments()
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 382, in goto_assignments

    results = self._goto()
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 408, in _goto
    user_stmt = self._parser.user_stmt()
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 293, in user_stmt

    module = self.module()
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 339, in module
    return self._parser().module
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/cache.py", line 143, in wrapper
    result = func(self)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/user_context.py", line 283, in _parser
    parser = FastParser(self._grammar, self._source, self._path)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 109, in __call__
    p.update(source)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 257, in update
    self._parse(source)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 383, in _parse
    line_offset, nodes)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 435, in _get_node
    p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 155, in __init__
    self.module = p.parse(self._tokenize(tokenizer))
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/pgen2/parse.py", line 106, in parse
    if self.addtoken(type, value, prefix, start_pos):
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/pgen2/parse.py", line 164, in addtoken
    self.pop()
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/pgen2/parse.py", line 196, in pop
    newnode = self.convert_node(self.grammar, type, children)
  File "/home/sebastian/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 205, in convert_node
    self._scope_names_stack[-1][n.value].remove(n)
AttributeError: 'Node' object has no attribute 'value'
```

I'm using vim from Ubuntu 14.04 repository.

**Comment by omikronsc** [comment]
Oh, sorry, it might be because I use Python 3 construct `[Foo(first) for first, *rest in items]` but jedi-vim is configured to use Python 2.7. However I can't verify it because setting 

`let g:jedi#force_py_version = 3` 

causes jedi to complain:

```
Error: jedi-vim failed to initialize Python: Could not setup g:jedi#force_py_version: jedi#setup_py_v
ersion: Vim(py3file):E319: Przykro mi, ale ta komenda nie jest dostępna w tej wersji: py3file /home/s
ebastian/.vim/bundle/jedi-vim/initialize.py (in function jedi#init_python..<SNR>27_init_python, wiers
z 6)
```

**Comment by davidhalter** [comment]
Jedi version?

**Comment by omikronsc** [comment]
I cloned this repository se jedi version is `HEAD detached at 995a653` as submodule is specified.

**Comment by kandinell** [comment]
I have same error in jedi version `625c568`
FYI, I'm using Elementary OS(Freya)

**Comment by davidhalter** [comment]
This was fixed (I'm too lazy to look up the issue) in Jedi. Is available on jedi's dev branch. Will be released soon.
