### ISSUE TITLE
Goto: local variable 'module_path' referenced before assignment

### ISSUE THREAD

**Issue by scribu** [davidhalter/jedi-vim#587]
Trying to jump to the ModelView definition on this line:

```python
from flask_admin.contrib.sqla import ModelView
```

Produces this:

```
Traceback (most recent call last):
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi_vim.py", line 117, in wrapper
    return func(*args, **kwargs)
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi_vim.py", line 229, in goto
    definitions = [x for x in script.goto_definitions()
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi/jedi/api/__init__.py", line 368, in goto_definitions
    definitions = resolve_import_paths(definitions)
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi/jedi/api/__init__.py", line 342, in resolve_import_paths
    scopes.update(resolve_import_paths(set(s.follow())))
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi/jedi/evaluate/imports.py", line 94, in follow
    types = importer.follow()
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi/jedi/evaluate/imports.py", line 252, in follow
    return self._do_import(self.import_path, self.sys_path_with_modifications())
  File "/Users/scribu/.config/nvim/plugged/jedi-vim/jedi/jedi/evaluate/imports.py", line 316, in _do_import
    if module_path is None:
UnboundLocalError: local variable 'module_path' referenced before assignment
```

Other jumps work fine.

```
:version
NVIM v0.1.5-86-g490804e
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=aut
o -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20160504-733-5gqt5o/build/config -I/tmp/neovim-20160504-733-5gqt5o/src -I/tmp/neovim-20160504-733-5gqt5o/deps-build/usr/include -I/tmp/neovim-20160504-733-5gqt5o/deps-bui
ld/usr/include -I/tmp/neovim-20160504-733-5gqt5o/deps-build/usr/include/luajit-2.0 -I/tmp/neovim-20160504-733-5gqt5o/deps-build/usr/include -I/tmp/neovim-20160504-733-5gqt5o/deps-build/usr/include -I/tmp/neovim-20160504-733-5gqt5o/deps
-build/usr/include -I/tmp/neovim-20160504-733-5gqt5o/deps-build/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20160504-733-5gqt5o/build/src/nvim/auto -I/tmp/neovim-20160504-733-5gqt5o/build/in
clude
Compiled by scribu@imac

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

```
:JediDebugInfo
Using Python Version: 3
```

Jedi revision: 6b7dfe1

**Comment by blueyed** [comment]
Thanks for the report.
It is a Jedi issue though, and I've created a PR (untested): https://github.com/davidhalter/jedi/pull/736

Could you check if that fixes the issue for you, please?

**Comment by blueyed** [comment]
@scribu 
See the reply on https://github.com/davidhalter/jedi/pull/736#issuecomment-228979578: it came up already a few times, but would need a test.
Could you provide this by chance?

Anyway, I am closing the jedi-vim issue, because it's a problem with Jedi.
