### ISSUE TITLE
Typing `<leader>d` on certain names crashes jedi-vim

### ISSUE THREAD

**Issue by gcavallanti** [davidhalter/jedi-vim#596]
If I type `<leader>d` from
 
    "~/Library/Python/2.7/lib/python/site-packages/jupyter_console/app.py" line 90 of 159 --56%-- col 16

(app.py being part of the jupyter-console package) a `KeyError` exception is raised (see listing  below)

The offending line is

    classes = [ZMQTerminalInteractiveShell] + JupyterConsoleApp.classes

and column 16 falls within the `ZMQTerminalInteractiveShell` name. `:pwd` shows:

    ~/Library/Python/2.7/lib/python/site-packages/jupyter_console

I am running macvim (see listing below) and python 2.7.12/jupyter-console 5.0.0 (see listing below), both installed via Homebrew.
The exception is raised even when Vim is started with the following basic vimrc file

    filetype off
    call pathogen#infect()
    filetype plugin indent on
    set nocompatible

and with no plugins in `~/.vim/bundle` other than jedi-vim. 

The Atom autocomplete-jedi plugin resolves the reference to `ZMQTerminalInteractiveShell` no prob and properly jumps to its definition in `ptshell.py`.

##### Jupyter console version
jupyter-console is installed with `pip install --user`.  `pip freeze` reports:

    ...
    jupyter==1.0.0
    jupyter-client==4.3.0
    jupyter-console==5.0.0
    jupyter-core==4.1.0
    ...

##### Vim version
    VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jul  6 2016 17:03:03)
    MacOS X (unix) version
    Included patches: 1-1831
    Compiled by Homebrew
    Huge version with MacVim GUI.  Features included (+) or not (-):
    +acl             +comments        +extra_search    +jumplist        +mouse_dec       +path_extra      +smartindent     +title           -X11
    +arabic          +conceal         +farsi           +keymap          -mouse_gpm       +perl            +startuptime     +toolbar         -xfontset
    +autocmd         +cryptv          +file_in_path    +langmap         -mouse_jsbterm   +persistent_undo +statusline      +transparency    +xim
    +balloon_eval    +cscope          +find_in_path    +libcall         +mouse_netterm   +postscript      -sun_workshop    +user_commands   -xsmp
    +browse          +cursorbind      +float           +linebreak       +mouse_sgr       +printer         +syntax          +vertsplit       -xterm_clipboard
    ++builtin_terms  +cursorshape     +folding         +lispindent      -mouse_sysmouse  +profile         +tag_binary      +virtualedit     -xterm_save
    +byte_offset     +dialog_con_gui  -footer          +listcmds        +mouse_urxvt     +python          +tag_old_static  +visual          -xpm
    +channel         +diff            +fork()          +localmap        +mouse_xterm     -python3         -tag_any_white   +visualextra
    +cindent         +digraphs        +fullscreen      +lua             +multi_byte      +quickfix        +tcl             +viminfo
    +clientserver    +dnd             -gettext         +menu            +multi_lang      +reltime         +termguicolors   +vreplace
    +clipboard       -ebcdic          -hangul_input    +mksession       -mzscheme        +rightleft       +terminfo        +wildignore
    +cmdline_compl   +emacs_tags      +iconv           +modify_fname    +netbeans_intg   +ruby            +termresponse    +wildmenu
    +cmdline_hist    +eval            +insert_expand   +mouse           +odbeditor       +scrollbind      +textobjects     +windows
    +cmdline_info    +ex_extra        +job             +mouseshape      +packages        +signs           +timers          +writebackup
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
      system gvimrc file: "$VIM/gvimrc"
        user gvimrc file: "$HOME/.gvimrc"
    2nd user gvimrc file: "~/.vim/gvimrc"
        system menu file: "$VIMRUNTIME/menu.vim"
      fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
    Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -F/usr/local/Cellar/python/2.7.11/Fra
    meworks -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.fr
    amework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.plat
    form/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Fr
    ameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib -F/usr/local/Cellar/python/2.7.11/Frameworks -L/usr/local/Cellar/python/2.7.11/Frameworks/Python
    .framework/Versions/2.7/lib/python2.7/config -lpython2.7 -framework CoreFoundation -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -l
    ncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local
    /Cellar/python/2.7.11/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby

##### Traceback
    Traceback (most recent call last):
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi_vim.py", line 117, in wrapper
        return func(*args, **kwargs)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi_vim.py", line 229, in goto
        definitions = [x for x in script.goto_definitions()
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 366, in goto_definitions
        definitions = set(self._prepare_goto(goto_path))
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 298, in _prepare_goto
        scopes = self._evaluator.eval_element(eval_stmt)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 169, in eval_element
        return self._eval_atom(element)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 230, in _eval_atom
        return self.find_types(scope, atom, stmt.start_pos, search_global=True)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 120, in find_types
        return f.find(scopes, search_global)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 52, in wrapper
        result = func(*args, **kwargs)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 87, in find
        types = self._names_to_types(names, search_global)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 233, in _names_to_types
        new_types = _name_to_types(self._evaluator, name, self.scope)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 282, in _name_to_types
        types += imports.ImportWrapper(evaluator, name).follow()
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 94, in follow
        types = importer.follow()
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
        rv = function(obj, *args, **kwargs)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 252, in follow
        return self._do_import(self.import_path, self.sys_path_with_modifications())
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 347, in _do_import
        module = _load_module(self._evaluator, module_path, source, sys_path)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 450, in _load_module
        module = load(source) if cached is None else cached.module
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/evaluate/imports.py", line 445, in load
        p = fast.FastParser(evaluator.grammar, common.source_to_unicode(source), p)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 106, in __call__
        p = super(CachedFastParser, self).__call__(grammar, source, module_path)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 243, in __init__
        self.update(source)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 257, in update
        self._parse(source)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 383, in _parse
        line_offset, nodes)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 435, in _get_node
        p = Parser(self._grammar, parser_code, self.module_path, tokenizer=tokenizer)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 155, in __init__
        self.module = p.parse(self._tokenize(tokenizer))
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/pgen2/parse.py", line 106, in parse
        if self.addtoken(type, value, prefix, start_pos):
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/pgen2/parse.py", line 170, in addtoken
        value, start_pos, prefix, self.addtoken)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 269, in error_recovery
        self._stack_removal(grammar, stack, index + 1, value, start_pos)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 304, in _stack_removal
        clear_names(children=node[1])
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 294, in clear_names
        clear_names(c.children)
      File "/Users/gcavallanti/.dotfiles/.vim/bundle/jedi-vim/jedi/jedi/parser/__init__.py", line 298, in clear_names
        self._scope_names_stack[-1][c.value].remove(c)
    KeyError: u'self'

**Comment by davidhalter** [comment]
Can you retry on the latest dev branch of Jedi? I'm pretty sure this issue has been fixed (this code doesn't even exist anymore AFIK).

**Comment by gcavallanti** [comment]
Turns out that even master is enough.  Apparently the recommended way to install jedi-vim (see `README.rst`), i.e., `git clone --recursive https://github.com/davidhalter/jedi-vim.git` points to an old commit (jedi @ 995a653).

**Comment by davidhalter** [comment]
It does. This is a commit close to the last release 0.9.0. I usually do releases for both PyPI and jedi-vim together.
