### ISSUE TITLE
Some jedi#usages() invocations cause AttributeError on MergedNamesDict

### ISSUE THREAD

**Issue by ches** [davidhalter/jedi-vim#599]
I have yet to surmise what the pattern is for cases that cause this, because most of the time `jedi#usages()` works, but I'm hoping a traceback is a good lead toward being to root it out:

```
Traceback (most recent call last):
  File "/Users/ches/.vim/bundle/jedi-vim/jedi_vim.py", line 119, in wrapper
    return func(*args, **kwargs)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi_vim.py", line 236, in goto
    definitions = script.usages()
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/api/__init__.py", line 490, in usages
    names = usages.usages(self._evaluator, definitions, module)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/api/usages.py", line 32, in usages
    result = evaluator.goto(name)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 369, in goto
    types = self.eval_element(call)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 183, in eval_element
    types = self._eval_atom(element.children[0])
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 86, in find
    names = self.filter_name(scopes)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 177, in filter_name
    names = self.names_dict_lookup(names_dict, position)
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/evaluate/finder.py", line 119, in names_dict_lookup
    names = names_dict[search_str]
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 78, in __getitem__
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
  File "/Users/ches/.vim/bundle/jedi-vim/jedi/jedi/parser/fast.py", line 78, in <genexpr>
    return list(chain.from_iterable(dct.get(value, []) for dct in self.dicts))
AttributeError: 'MergedNamesDict' object has no attribute 'get'
```

**Comment by davidhalter** [comment]
I think you're on 0.9.0? This bug was fixed: https://github.com/davidhalter/jedi/issues/589

**Comment by ches** [comment]
I'm up-to-date with latest master of jedi-vim if I'm not mistaken:

```
$ pwd
/Users/ches/.vim/bundle/jedi-vim

[ches@Fio]$ git --no-pager show --no-patch
commit c94a143bfb18f59095963fcde4184a164fd1d1f0
Author: Dave Halter <davidhalter88@gmail.com>
Date:   Sat Jul 30 15:59:15 2016 +0200

    VIM apparently cannot deal with zero bytes in strings. Fixes #551

[ches@Fio]$ git submodule update --recursive

[ches@Fio]$ stat': git submodule status
 995a6531225ba0b65e1ff863d97e5404d989047b jedi (v0.9.0-19-g995a653)
```

Looks like jedi-vim's submodule version of jedi is indeed 11 months old, davidhalter/jedi@995a6531225ba0b65e1ff863d97e5404d989047b. Am I missing something?

**Comment by blueyed** [comment]
@ches 
The submodule has not been updated yet.. but you can checkout master there manually, of course.

I think that @davidhalter plans to update the submodule with the next Jedi release?!

**Comment by blueyed** [comment]
FWIW, the submodule was updated for deoplete-jedi a while ago: https://github.com/zchee/deoplete-jedi/commit/c12f7b214421d0140b7029f3485dd10a93eb2484.

**Comment by davidhalter** [comment]
@blueyed Yes I do.

**Comment by ches** [comment]
I see, yes manually checking out master of the submodule of course fixes it. @davidhalter's initial comment made me assume there must be a newer stable version already, I'm only an occasional Python programmer so I don't follow the development closely.

Thanks.

**Comment by davidhalter** [comment]
@ches Sure, I don't expect you to. I just close issues that are solved in the development branch, because otherwise I lose oversight.

**Comment by ches** [comment]
@davidhalter Actually this and reading about your interest in refactoring APIs does raise a question if I find some hacking time, forgive me if this is mentioned somewhere but I didn't see it in the Jedi development docs: what is your distinction for the `master` versus `dev` branches? `dev` is latest work but whatever is on master will definitely be in the next tagged stable release whenever it happens, something like that?

It might be good to mention somewhere what contributors should base pull requests from (again maybe I've overlooked it).

**Comment by davidhalter** [comment]
@ches It's in `CONTRIBUTING.md`. Dev is just the non-stable stuff where master is mostly stable. I prefer pull requests on dev, because they might raise other issues.

**Comment by ches** [comment]
Ah, should have been an obvious place to find it, thanks 😇
