### ISSUE TITLE
PR #640 introduced regression in Python3 autocomplete

### ISSUE THREAD

**Issue by wlonk** [davidhalter/jedi-vim#641]
### Issue

In a Python3 environment, the `call_signature_escape` set in #640 causes autocomplete to break, with an exception coming from somewhere in the Python stdlib's `sre_parse`, "Nothing to repeat at position 0", emitting garbage into the vim buffer.

I don't understand the context and rationale for the change in that PR enough to be confident changing it to something else myself, but I hope this issue will shed light on the problem to one more informed than I!

### Steps to reproduce

```
$ mkvirtualenv --python=$(which python3) sample_env
$ vim foo.py
```

In vim, type `""." and watch autocomplete blow up.

### Versions

 - jedi-vim: 671f9f57804e9d47b50db3487fcb128eefc0db5d (does not appear in f191ccd6fb7f3bc2272a34d6230487caf64face7)
 - Vim / Neovim: 8.0.0124
 - Python: 3.5.2

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of the "JediDebugInfo" command (in a Python buffer)

```
Using Python version: 3
 - sys.version: 3.5.2 (default, Oct 11 2016, 04:59:56), [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
 - site module: /usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site.py
Jedi path: /Users/kit/.vim/bundle/jedi-vim/jedi/jedi/__init__.py
Jedi version: 0.10.0
jedi-vim git version: 0.8.0-54-g671f9f5
jedi git submodule status:  2ba78ab725f1e02dfef8bc50b0204cf656e8ee23 jedi (v0.9.0-547-g2ba78ab7)
```

### Output of the "messages" Vim command

After running the steps to reproduce:

```

Messages maintainer: Bram Moolenaar <Bram@vim.org>
Traceback (most recent call last):
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 340, in clear_call_signatures
    match = re.search(py_regex, line)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0

Traceback (most recent call last):
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 340, in clear_call_signatures
    match = re.search(py_regex, line)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0

Traceback (most recent call last):
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 340, in clear_call_signatures
    match = re.search(py_regex, line)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0

Traceback (most recent call last):
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 340, in clear_call_signatures
    match = re.search(py_regex, line)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0

Back at original
Traceback (most recent call last):
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/Users/kit/.vim/bundle/jedi-vim/jedi_vim.py", line 340, in clear_call_signatures
    match = re.search(py_regex, line)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 173, in search
    return _compile(pattern, flags).search(string)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0
```

### Output of "scriptnames" Vim command

Yeah, it's a lot…

```
  1: ~/.vimrc
  2: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/ftoff.vim
  3: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
  4: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
  5: ~/.vim/filetype.vim
  6: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/filetype.vim
  7: ~/.vim/bundle/vim-pug/ftdetect/pug.vim
  8: ~/.vim/bundle/Vim-Jinja2-Syntax/ftdetect/jinja.vim
  9: ~/.vim/bundle/vim-markdown/ftdetect/markdown.vim
 10: ~/.vim/bundle/vim-javascript/ftdetect/javascript.vim
 11: ~/.vim/bundle/vim-jsx/ftdetect/javascript.vim
 12: ~/.vim/bundle/vim-mustache-handlebars/ftdetect/mustache.vim
 13: ~/.vim/bundle/rust.vim/ftdetect/rust.vim
 14: ~/.vim/bundle/choicescript.vim/ftdetect/choicescript.vim
 15: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/ftplugin.vim
 16: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/indent.vim
 17: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/syntax/syntax.vim
 18: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/syntax/synload.vim
 19: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/syntax/syncolor.vim
 20: ~/.vim/bundle/vim-colorschemes/colors/hybrid_reverse.vim
 21: ~/.vim/bundle/vim-gitgutter/plugin/gitgutter.vim
 22: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/highlight.vim
 23: ~/.vim/bundle/vim-closetag/plugin/closetag.vim
 24: ~/.vim/bundle/vim-sort-motion/plugin/sort_motion.vim
 25: ~/.vim/bundle/ctrlp.vim/plugin/ctrlp.vim
 26: ~/.vim/bundle/ctrlp.vim/autoload/ctrlp/mrufiles.vim
 27: ~/.vim/bundle/supertab/plugin/supertab.vim
 28: ~/.vim/bundle/vim-buffergator/plugin/buffergator.vim
 29: ~/.vim/bundle/python-mode/plugin/pymode.vim
 30: ~/.vim/bundle/python-mode/autoload/pymode.vim
 31: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 32: ~/.vim/bundle/powerline/powerline/bindings/vim/plugin/powerline.vim
 33: ~/.vim/bundle/vim-tmuxify/plugin/tmuxify.vim
 34: ~/.vim/bundle/vim-pony/plugin/pony.vim
 35: ~/.vim/bundle/vim-indent-object/plugin/indent-object.vim
 36: ~/.vim/bundle/dash.vim/plugin/dash.vim
 37: ~/.vim/bundle/dash.vim/autoload/dash.vim
 38: ~/.vim/bundle/dash.vim/autoload/dash/defaults.vim
 39: ~/.vim/bundle/gundo.vim/plugin/gundo.vim
 40: ~/.vim/bundle/vim-dispatch/plugin/dispatch.vim
 41: ~/.vim/bundle/vim-commentary/plugin/commentary.vim
 42: ~/.vim/bundle/vim-obsession/plugin/obsession.vim
 43: ~/.vim/bundle/vim-surround/plugin/surround.vim
 44: ~/.vim/bundle/argtextobj.vim/plugin/argtextobj.vim
 45: ~/.vim/bundle/tabular/plugin/Tabular.vim
 46: ~/.vim/bundle/emmet-vim/plugin/emmet.vim
 47: ~/.vim/bundle/rust.vim/plugin/rust.vim
 48: ~/.vim/bundle/vim-racer/plugin/racer.vim
 49: ~/.vim/bundle/choicescript.vim/plugin/choicescript.vim
 50: ~/.vim/bundle/ack.vim/plugin/ack.vim
 51: ~/.vim/bundle/vim-fugitive/plugin/fugitive.vim
 52: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/getscriptPlugin.vim
 53: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/gzip.vim
 54: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/logiPat.vim
 55: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/manpager.vim
 56: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/matchparen.vim
 57: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/netrwPlugin.vim
 58: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/rrhelper.vim
 59: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/spellfile.vim
 60: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/tarPlugin.vim
 61: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/tohtml.vim
 62: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/vimballPlugin.vim
 63: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/plugin/zipPlugin.vim
 64: ~/.vim/bundle/tabular/after/plugin/TabularMaps.vim
 65: ~/.vim/bundle/tabular/autoload/tabular.vim
 66: ~/.vim/bundle/python-mode/ftplugin/python/pymode.vim
 67: ~/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim
 68: ~/.vim/bundle/python-mode/autoload/pymode/breakpoint.vim
 69: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 70: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 71: ~/.vim/bundle/pytest.vim/ftplugin/python/pytest.vim
 72: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/ftplugin/python.vim
 73: ~/.vim/bundle/python-mode/after/ftplugin/python.vim
 74: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 75: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/indent/python.vim
 76: ~/.vim/bundle/python-mode/after/indent/python.vim
 77: ~/.vim/bundle/python-mode/syntax/python.vim
 78: /usr/local/Cellar/vim/8.0.0124/share/vim/vim80/syntax/python.vim
 79: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 80: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter.vim
 81: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/utility.vim
 82: ~/.vim/bundle/vim-gitgutter/autoload/gitgutter/hunk.vim
 83: ~/.vim/bundle/python-mode/autoload/pymode/folding.vim
 84: ~/.vim/bundle/python-mode/autoload/pymode/lint.vim
 85: ~/.vim/bundle/python-mode/autoload/pymode/tools/signs.vim
 86: ~/.vim/bundle/python-mode/autoload/pymode/tools/loclist.vim
```

**Comment by wlonk** [comment]
(For now, I'm working around this by leaving

```
let g:jedi#call_signature_escape="'=`='"
```

in my `.vimrc`.)
