### ISSUE TITLE
Rename causes AttributeError: 'Definition' object has no attribute 'start_pos'

### ISSUE THREAD

**Issue by balta2ar** [davidhalter/jedi-vim#671]
### Issue

Renaming causes this stacktrace:
```
Traceback (most recent call last):
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 544, in rename
    return do_rename(replace)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 569, in do_rename
    key=lambda x: (x.module_path, x.start_pos))
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 569, in <lambda>
    key=lambda x: (x.module_path, x.start_pos))
AttributeError: 'Definition' object has no attribute 'start_pos'

Press ENTER or type command to continue
```
### Steps to reproduce

I'm not sure yet, sorry...

### Versions

 - jedi-vim: I think it's latest. I updated all vim plugins using dein#update() on these days.
 - Vim / Neovim: NVIM v0.2.0-1-g9956bee
 - Python: 2.7

In case you are not using jedi-vim from Git master, please test it there, too.

### Output of the "JediDebugInfo" command (in a Python buffer)
```
#### Jedi-vim debug information
Using Python version: 2
 - sys.version: 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40), [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
 - site module: /home/ybochkarev/miniconda/lib/python2.7/site.pyc
Jedi path: /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/pymode/libs
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein
    - /home/ybochkarev/dev/cs/trunk
    - /home/ybochkarev/miniconda/lib/python27.zip
    - /home/ybochkarev/miniconda/lib/python2.7
    - /home/ybochkarev/miniconda/lib/python2.7/plat-linux2
    - /home/ybochkarev/miniconda/lib/python2.7/lib-tk
    - /home/ybochkarev/miniconda/lib/python2.7/lib-old
    - /home/ybochkarev/miniconda/lib/python2.7/lib-dynload
    - /home/ybochkarev/.local/lib/python2.7/site-packages
    - /home/ybochkarev/miniconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg
    - /home/ybochkarev/miniconda/lib/python2.7/site-packages
    - _vim_path_
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/autoload/../python
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/pymode/libs/astroid/brain
    - .
    - ..
jedi-vim git version: fatal: Not a git repository (or any of the parent directories): .git
jedi git submodule status: fatal: Not a git repository (or any of the parent directories): .git

##### Settings
g:force_py_version = '2' (default: 'auto')
g:popup_select_first = 0 (default: 1)
g:documentation_command = '<leader>jk' (default: 'K')
g:usages_command = '<leader>ju' (default: '<leader>n')
g:completions_command = '' (default: '<C-Space>')
g:popup_on_dot = 0 (default: 1)
g:rename_command = '<leader>jr' (default: '<leader>r')
g:auto_vim_configuration = 0 (default: 1)
g:goto_assignments_command = '<leader>ja' (default: '<leader>g')
g:show_call_signatures_delay = 0 (default: 500)
g:goto_definitions_command = '<leader>jd' (default: '')
g:show_call_signatures = '2' (default: 1)
g:completions_enabled = 0 (default: 1)

  omnifunc=pythoncomplete#Complete
        Last set from ~/rc.arch/bz/.vim/init.vim
  completeopt=longest,menuone
        Last set from ~/.cache/dein/.cache/init.vim/.dein/autoload/deoplete/mapping.vim
```
### Output of the "messages" Vim command
```
Traceback (most recent call last):
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 544, in rename
    return do_rename(replace)
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 569, in do_rename
    key=lambda x: (x.module_path, x.start_pos))
  File "/home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi_vim.py", line 569, in <lambda>
    key=lambda x: (x.module_path, x.start_pos))
AttributeError: 'Definition' object has no attribute 'start_pos'
 - sys.version: 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40), [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
 - site module: /home/ybochkarev/miniconda/lib/python2.7/site.pyc
Jedi path: /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/jedi/jedi/__init__.py
 - version: 0.10.0
 - sys_path:
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/pymode/libs
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein
    - /home/ybochkarev/dev/cs/trunk
    - /home/ybochkarev/miniconda/lib/python27.zip
    - /home/ybochkarev/miniconda/lib/python2.7
    - /home/ybochkarev/miniconda/lib/python2.7/plat-linux2
    - /home/ybochkarev/miniconda/lib/python2.7/lib-tk
    - /home/ybochkarev/miniconda/lib/python2.7/lib-old
    - /home/ybochkarev/miniconda/lib/python2.7/lib-dynload
    - /home/ybochkarev/.local/lib/python2.7/site-packages
    - /home/ybochkarev/miniconda/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg
    - /home/ybochkarev/miniconda/lib/python2.7/site-packages
    - _vim_path_
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/autoload/../python
    - /home/ybochkarev/.cache/dein/.cache/init.vim/.dein/pymode/libs/astroid/brain
    - .
    - ..
Press ENTER or type command to continue
```

### Output of "scriptnames" Vim command

There are 313 of them, more than 100 plugins are active ATM. If you could tell me how to redirect the output into a file, I would have shown them here gladly (if relevant).

**Comment by davidhalter** [comment]
Good point, thanks. I think `start_pos` was deprecated a few versions ago and has been removed in Jedi 0.10.0.
