### ISSUE TITLE
jedi#usages_command => jedi_vim.VimError: Vim(loadview):E32: No file name; created by: 'jedi#add_goto_window(2)'？

### ISSUE THREAD

**Issue by ghost** [davidhalter/jedi-vim#688]
When I tried to find all usages of a name by typing `<leader>n`, jedi-vim give me folloing error:

```vim
Traceback (most recent call last):                                                                                                                                                    
  File "/home/ormsf/.vim/bundle/jedi-vim/jedi_vim.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/home/ormsf/.vim/bundle/jedi-vim/jedi_vim.py", line 297, in goto
    vim_eval('jedi#add_goto_window(' + str(len(lst)) + ')')
  File "/home/ormsf/.vim/bundle/jedi-vim/jedi_vim.py", line 80, in vim_eval
    return _catch_exception(string, True)
  File "/home/ormsf/.vim/bundle/jedi-vim/jedi_vim.py", line 71, in _catch_exception
    raise VimError(result['exception'], result['throwpoint'], string)
jedi_vim.VimError: Vim(loadview):E32: No file name; created by: 'jedi#add_goto_window(2)'
```

**Running Enviroment:**
Ubuntu16.04 + Python3.5 + Vim7.4

Can anyone give me some suggestions to solve this problem?

**Comment by ormsf** [comment]
I have fixed this error by removing:
```vim
" au BufWinLeave * mkview
" au BufWinEnter * silent loadview
```
in my `~/.vimrc`

Can anyone explain me why this error happan?

**Comment by blueyed** [comment]
Does it happen always?
Do you have a test case to reproduce it?
Do you use custom settings?

**Comment by davidhalter** [comment]
Hasn't been answered. closing.
