### ISSUE TITLE
py.test failed on Python3

### ISSUE THREAD

**Issue by sein-tao** [davidhalter/jedi-vim#723]
### Issue
`py.test` failed when execute with Python 3.6.1, as the test code seems lack of Python3 compatibility.

### Steps to reproduce
run Python3 `py.test` from `jedi-vim` directory.
``` 
cd ~/.vim/bundle/jedi-vim
py.test
```
notice that py.test is from Python3.
`cat /usr/bin/py.test`:
```output
#!/usr/bin/python3

# -*- coding: utf-8 -*-
import re
import sys

from pytest import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

### Error Info
`urllib` error, which is a common issue for Python 2to3 compatibility.
when this one is fixed, other errors like str/bytes issue pop out. 

error info from `py.test`
```output
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 101, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/config.py", line 912, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 750, in call_historic
INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/cygdrive/d/xuyu/.vim/bundle/jedi-vim/conftest.py", line 36, in pytest_configure
INTERNALERROR>     name, hdrs = urllib.urlretrieve(VSPEC_URL)
INTERNALERROR> AttributeError: module 'urllib' has no attribute 'urlretrieve'
```

**Comment by blueyed** [comment]
Thanks for the report.
The tests are broken since a while already also on Python 2.

**Comment by blueyed** [comment]
This should be fixed by now.
