### ISSUE TITLE
jedi-vim causes error upon starting vim

### ISSUE THREAD

**Issue by TheChymera** [davidhalter/jedi-vim#725]
After installing jedi-vim I get the following error when I start vim:

```
Error detected while processing function jedi#init_python:
line    7:
Error: jedi-vim failed to initialize Python: jedi#setup_py_version: Vim(py3file):Traceback (most recent call las
t): (in function jedi#init_python[3]..<SNR>35_init_python[50]..jedi#setup_py_version, line 16)
```

Installation itself was a bit difficult, as I had to remove the test specification from the makefile, in order for the build not to fail. Having left `py.test` in the Makefile, I would have gotten:

```
zenbookhost ~ # emerge -v app-vim/jedi

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    *] app-vim/jedi-9999::chymeric  PYTHON_TARGETS="python2_7 python3_4" 0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB


>>> Verifying ebuild manifests

>>> Emerging (1 of 1) app-vim/jedi-9999::chymeric
>>> Unpacking source...
 * Fetching git://github.com/davidhalter/jedi-vim.git ...
git fetch git://github.com/davidhalter/jedi-vim.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/app-vim/jedi/0/__main__ refs/git-r3/HEAD
 * Fetching https://github.com/davidhalter/jedi.git ...
git fetch https://github.com/davidhalter/jedi.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/app-vim/jedi/0/jedi/__main__ 5427b02712828b2875d35b5ee1c8b5e58f820537
 * Checking out git://github.com/davidhalter/jedi-vim.git to /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999 ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               git://github.com/davidhalter/jedi-vim.git
   at the commit:            6411de0cd1d2a2959f5a0bf977b3f8ecea2209d0
 * Checking out https://github.com/davidhalter/jedi.git to /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999/jedi ...
git checkout --quiet 5427b02712828b2875d35b5ee1c8b5e58f820537
GIT update -->
   repository:               https://github.com/davidhalter/jedi.git
   at the commit:            5427b02712828b2875d35b5ee1c8b5e58f820537
>>> Source unpacked in /var/tmp/portage/app-vim/jedi-9999/work
>>> Preparing source in /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999 ...
 * Will copy sources from /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999
 * python2_7: copying to /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999-python2_7
 * python3_4: copying to /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999-python3_4
LALALAL
sed: -e expression #1, char 1: unknown command: `-'
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999 ...
make -j5 
py.test
============================================= test session starts ==============================================
platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.33, pluggy-0.4.0
rootdir: /var/tmp/portage/app-vim/jedi-9999/work/jedi-9999, inifile: pytest.ini
collected 7 items 

test_integration.py ...FF.F

=================================================== FAILURES ===================================================
___________________________________________ test_integration[case3] ____________________________________________
test/completions.vim failed:
No protocol specified
ok 1 - completions smart import
ok 2 - completions no smart import after space=jedi#complete_opened(0)
=jedi#complete_opened(0)

ok 3 - completions import=jedi#complete_opened(0)
=jedi#complete_opened(0)

ok 4 - completions exception=jedi#complete_opened(0)
=jedi#complete_opened(0)
=jedi#complete_opened(0)

ok 5 - completions dot_open=jedi#complete_opened(0)

not ok 6 - completions cycling through entries
# Expected getline('.') == 'raise ImportWarning'
#       Actual value: "raise imp"
#     Expected value: "raise ImportWarning"
1..6

___________________________________________ test_integration[case4] ____________________________________________

case = <<class 'conftest.IntegrationTestFile'>: test/signatures.vim>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch instance at 0x7f3044c6cdd0>
pytestconfig = <_pytest.config.Config object at 0x7f30454506d0>

    def test_integration(case, monkeypatch, pytestconfig):
>       case.run()

test_integration.py:2: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <<class 'conftest.IntegrationTestFile'>: test/signatures.vim>

    def run(self):
        output = subprocess.check_output(
            [VSPEC_RUNNER, '.', VSPEC_FOLDER, self.path])
        for line in output.splitlines():
            if line.startswith(b'not ok') or line.startswith(b'Error'):
                pytest.fail("{0} failed:\n{1}".format(
>                   self.path, output.decode('utf-8')), pytrace=False)
E               UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 2693: ordinal not in range(128)

conftest.py:25: UnicodeEncodeError
___________________________________________ test_integration[case6] ____________________________________________
test/goto.vim failed:
No protocol specified
3 more lines
not ok 1 - goto_simple goto_definitions
# Expected line('.') == 1
#       Actual value: 3
#     Expected value: 1
3 more lines
not ok 2 - goto_simple goto_assignments
# Expected line('.') == 2
#       Actual value: 3
#     Expected value: 2
ok 3 - goto_with_tabs follow_import
ok 4 - goto_with_tabs multi_definitions
Traceback (most recent call last):
  File "/var/tmp/portage/app-vim/jedi-9999/work/jedi-9999/jedi_vim.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "/var/tmp/portage/app-vim/jedi-9999/work/jedi-9999/jedi_vim.py", line 670, in new_buffer
    vim_command('w')
  File "/var/tmp/portage/app-vim/jedi-9999/work/jedi-9999/jedi_vim.py", line 76, in vim_command
    _catch_exception(string, False)
  File "/var/tmp/portage/app-vim/jedi-9999/work/jedi-9999/jedi_vim.py", line 71, in _catch_exception
    raise VimError(result['exception'], result['throwpoint'], string)
jedi_vim.VimError: Vim(write):E32: No file name; created by: 'w'
not ok 5 - goto_with_buffers no_new_tabs
# function <SNR>1_main[9]..vspec#test[6]..<SNR>2_run_suites[9]..20, line 4
# Vim(python):E319: Sorry, the command is not available in this version:         python jedi_vim.goto()
ok 6 - goto_with_buffers multi_definitions
not ok 7 - goto_with_splits follow_import
# Expected getline('.') == 'import subprocess'
#       Actual value: "subprocess"
#     Expected value: "import subprocess"
"/usr/lib64/python3.4/subprocess.py" 
"/usr/lib64/python3.4/subprocess.py" [readonly] 1695L, 64352C
ok 8 - goto_wildignore restores_wildignore
"/usr/lib64/python3.4/subprocess.py" 
"/usr/lib64/python3.4/subprocess.py" [readonly] 1695L, 64352C
ok 9 - goto_wildignore not_using_tagstack
1..9

====================================== 3 failed, 4 passed in 3.13 seconds ======================================
make: *** [Makefile:2: test] Error 1
 * ERROR: app-vim/jedi-9999::chymeric failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-vim/jedi-9999::chymeric'`,
 * the complete build log and the output of `emerge -pqv '=app-vim/jedi-9999::chymeric'`.
 * The complete build log is located at '/var/tmp/portage/app-vim/jedi-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-vim/jedi-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/app-vim/jedi-9999/work/jedi-9999'
 * S: '/var/tmp/portage/app-vim/jedi-9999/work/jedi-9999'

>>> Failed to emerge app-vim/jedi-9999, Log file:

>>>  '/var/tmp/portage/app-vim/jedi-9999/temp/build.log'

 * Messages for package app-vim/jedi-9999:

 * ERROR: app-vim/jedi-9999::chymeric failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-vim/jedi-9999::chymeric'`,
 * the complete build log and the output of `emerge -pqv '=app-vim/jedi-9999::chymeric'`.
 * The complete build log is located at '/var/tmp/portage/app-vim/jedi-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-vim/jedi-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/app-vim/jedi-9999/work/jedi-9999'
 * S: '/var/tmp/portage/app-vim/jedi-9999/work/jedi-9999'
 * 
 * The following package has failed to build, install, or execute postinst:
 * 
 *  (app-vim/jedi-9999:0/0::chymeric, ebuild scheduled for merge), Log file:
 *   '/var/tmp/portage/app-vim/jedi-9999/temp/build.log'
 * 
```

I cannot tell exactly whether jedi-vim is working after the error message - at any rate pressing `ctrl+space` starts no autocompletion.

If anyone of you is familiar with Gentoo, this is the ebuild I am using:

```
EAPI=5
PYTHON_COMPAT=( python2_7 python3_4 )
inherit vim-plugin git-r3 python-r1 python-utils-r1

DESCRIPTION="Jedi Python autocompletion with VIM"
HOMEPAGE="https://github.com/davidhalter/jedi-vim"
SRC_URI=""
EGIT_REPO_URI="git://github.com/davidhalter/${PN}-vim.git"

LICENSE="LGPL-3+"
KEYWORDS=""
IUSE=""

RDEPEND="dev-python/jedi[${PYTHON_USEDEP}]"
DEPEND="app-editors/vim[python]"

#REQUIRED_USE="${PYTHON_REQUIRED_USE}"

src_prepare() {
	python_copy_sources
	sed -i -e '1,3d' Makefile
}

src_install() {
	python_foreach_impl python_domodule jedi_vim.py
	vim-plugin_src_install
}
```

**Comment by davidhalter** [comment]
Please use the template. It exists for a reason. We know that tests are broken. There's an issue for it.

Please open a new issue including all the stuff in the template.
