### ISSUE TITLE
Error when finding definition of a ModuleAttributeName

### ISSUE THREAD

**Issue by kidhanis** [davidhalter/jedi-vim#737]
### Issue

Calling `jedi#goto_assignments()` on any of the four items on the `name` list in [jedi/evaluate/representation.py](
https://github.com/davidhalter/jedi/blob/3789709ec086b1191fcc76eed788aa04c5054d4d/jedi/evaluate/representation.py#L489) throws the error message below. If `d` is of type `jedi.api.classes.Definition`  and `d._name` is of type `jedi.evaluate.representation.ModuleAttributeName`, then the value of `d.column` will be `None`. Just in case, I also started with `vim -u NONE` and got the same results.

### Steps to reproduce

For example, simply write

 `__name__`

in a new file. Then `:call jedi#goto_assignments()` with `__name__` under the cursor.

#### Jedi-vim debug information
Using Python version: 3
 - sys.version: `3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)]`
 - site module: `C:\\Python36\\Lib\\site.py`
Jedi path: `C:\\Python36\\lib\\site-packages\\jedi\\__init__.py`
 - version: 0.10.2
 - sys_path:
    - `C:\\Users\\Admin\\%PYTHONPATH%`
    - `C:\\Users\\Admin`
    - `C:\\Python36\\python36.zip`
    - `C:\\Python36\\Lib`
    - `C:\\Python36\\DLLs`
    - `C:\\Program Files\\Vim\\vim80`
    - `C:\\Python36`
    - `C:\\Python36\\lib\\site-packages`
    - `_vim_path_`
 - jedi-vim git version: 0.8.0-96-g0c6a2b7
 - jedi git submodule status: -5427b02712828b2875d35b5ee1c8b5e58f820537 pythonx/jedi

##### Settings
```
  omnifunc=jedi#completions
	Last set from ~\vimfiles\bundle\jedi-vim\after\ftplugin\python\jedi.vim
  completeopt=menuone,longest,preview
	Last set from ~\vimfiles\bundle\jedi-vim\plugin\jedi.vim
```

#### :version
```

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 29 2017 14:59:54)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-517
Compiled by hp@HP-PC
Huge version with GUI.  Features included (+) or not (-):
+acl                +eval               +mouse              +syntax
+arabic             +ex_extra           +mouseshape         +tag_binary
+autocmd            +extra_search       +multi_byte_ime/dyn +tag_old_static
+balloon_eval       +farsi              +multi_lang         -tag_any_white
+browse             +file_in_path       +mzscheme/dyn       +tcl/dyn
++builtin_terms     +find_in_path       +netbeans_intg      -termguicolors
+byte_offset        +float              +num64              -tgetent
+channel            +folding            +ole                -termresponse
+cindent            -footer             +packages           +textobjects
+clientserver       +gettext/dyn        +path_extra         +timers
+clipboard          -hangul_input       +perl/dyn           +title
+cmdline_compl      +iconv/dyn          +persistent_undo    +toolbar
+cmdline_hist       +insert_expand      -postscript         +user_commands
+cmdline_info       +job                +printer            +vertsplit
+comments           +jumplist           +profile            +virtualedit
+conceal            +keymap             +python/dyn         +visual
+cryptv             +lambda             +python3/dyn        +visualextra
+cscope             +langmap            +quickfix           +viminfo
+cursorbind         +libcall            +reltime            +vreplace
+cursorshape        +linebreak          +rightleft          +wildignore
+dialog_con_gui     +lispindent         +ruby/dyn           +wildmenu
+diff               +listcmds           +scrollbind         +windows
+digraphs           +localmap           +signs              +writebackup
+directx            +lua/dyn            +smartindent        -xfontset
-dnd                +menu               +startuptime        -xim
-ebcdic             +mksession          +statusline         +xpm_w32
+emacs_tags         +modify_fname       -sun_workshop       -xterm_save
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501  /Fo.\ObjGXOULYHTRZAMD64/ /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /MD -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DGLOBAL_IME -DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python36.dll\" -DFEAT_MZSCHEME -I "C:\Users\hp\Desktop\racket-x64\include" -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracketxxxxxxx.dll\" -DDYNAMIC_MZGC_DLL=\"libmzgcxxxxxxx.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64  msvcrt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python36.lib   "C:\TCL\lib\tclstub86.lib" WSock32.lib .\xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug
```

#### :messages
```
"~\test.py" 0L, 0C

Traceback (most recent call last):
  File "C:\Users\Admin\vimfiles\bundle\jedi-vim\pythonx\jedi_vim.py", line 128, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Admin\vimfiles\bundle\jedi-vim\pythonx\jedi_vim.py", line 276, in goto
    'call cursor({0}, {1})'.format(d.line, d.column + 1))) as f:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

```

<details><summary>:scriptnames</summary>

```
  1: ~\vimfiles\vimrc
  2: C:\Program Files\Vim\vim80\syntax\syntax.vim
  3: C:\Program Files\Vim\vim80\syntax\synload.vim
  4: C:\Program Files\Vim\vim80\syntax\syncolor.vim
  5: C:\Program Files\Vim\vim80\filetype.vim
  6: C:\Program Files\Vim\vim80\menu.vim
  7: C:\Program Files\Vim\vim80\autoload\paste.vim
  8: ~\vimfiles\autoload\pathogen.vim
  9: C:\Program Files\Vim\vim80\ftoff.vim
 10: ~\vimfiles\bundle\jedi-vim\plugin\jedi.vim
 11: C:\Program Files\Vim\vim80\ftplugin.vim
 12: C:\Program Files\Vim\vim80\plugin\getscriptPlugin.vim
 13: C:\Program Files\Vim\vim80\plugin\gzip.vim
 14: C:\Program Files\Vim\vim80\plugin\logiPat.vim
 15: C:\Program Files\Vim\vim80\plugin\manpager.vim
 16: C:\Program Files\Vim\vim80\plugin\matchparen.vim
 17: C:\Program Files\Vim\vim80\plugin\netrwPlugin.vim
 18: C:\Program Files\Vim\vim80\plugin\rrhelper.vim
 19: C:\Program Files\Vim\vim80\plugin\spellfile.vim
 20: C:\Program Files\Vim\vim80\plugin\tarPlugin.vim
 21: C:\Program Files\Vim\vim80\plugin\tohtml.vim
 22: C:\Program Files\Vim\vim80\plugin\vimballPlugin.vim
 23: C:\Program Files\Vim\vim80\plugin\zipPlugin.vim
 24: ~\vimfiles\gvimrc
 25: C:\Program Files\Vim\vim80\syntax\python.vim
 26: ~\vimfiles\bundle\jedi-vim\after\syntax\python.vim
 27: ~\vimfiles\bundle\jedi-vim\autoload\jedi.vim
 28: ~\vimfiles\bundle\jedi-vim\ftplugin\python\jedi.vim
 29: C:\Program Files\Vim\vim80\ftplugin\python.vim
 30: ~\vimfiles\bundle\jedi-vim\after\ftplugin\python\jedi.vim
```
</details>

**Comment by davidhalter** [comment]
Good point. This is actually a jedi-vim issue not Jedi. Jedi seems to be correct here.

**Comment by davidhalter** [comment]
This was solved somewhere along the line, thanks again for reporting it.
