### ISSUE TITLE
Update `urllib.request` usage

### ISSUE THREAD

**Issue by TheChymera** [davidhalter/jedi-vim#753]
I am trying to build jedi-vim on a system using `urllib3-1.22`.

Your `Makefile` calls `py.test`, which fails with the following:

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/_pytest/config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/lib64/python2.7/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/usr/lib64/python2.7/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/usr/lib64/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/var/tmp/portage/app-vim/jedi-0.8_p20171015/work/jedi-vim-77924398bd594e238766153cec97ace62650f082/conftest.py", line 3, in <module>
    import urllib.request
ImportError: No module named request
ERROR: could not load /var/tmp/portage/app-vim/jedi-0.8_p20171015/work/jedi-vim-77924398bd594e238766153cec97ace62650f082/conftest.py
```

Apparently this [is because the `urllib.requests` module has been deprecated](https://stackoverflow.com/a/42379032/1893275). I suspect this may be easily addressed by importing all functions by name, and catching the `ImportError` if the module does not exist.

I can write a pr if you would be interested to pull.

**Comment by davidhalter** [comment]
urllib.requests was not deprecated. Just look at the Python 3 documentation. Just install Python 3 and dump your legacy Python :)
