### ISSUE TITLE
Unexpectedly property evaluation

### ISSUE THREAD

**Issue by fujiisoup** [davidhalter/jedi-vim#757]
### Issue

Jedi built in IPython seems to evaluate properties of objects in auto-completion.
This is reported in an xarray issue pydata/xarray#1727, 
where we have a function that is triggered by an evaluation of a certain property.

If there is a possible workaround to avoid the property evaluation,
it would be appreciated.

### Steps to reproduce

Minimal working example is

1. Save the following as example.py
```python
import traceback

class ExampleClass(object):
    def __init__(self):
        pass

    @property
    def value(self):
        print('value called')
        print(traceback.print_exc())
        # In xarray, we do some heavy things here.
        # We do not want to call this property unless users want.
```
Then, in IPython

```python
In [1]: import example

In [2]: ex = example.ExampleClass()

In [3]: ex.val  -> press [Tab]
value called
Traceback (most recent call last):
None
KeyError: (('value',), frozenset())
  File "/home/keisukefujii/anaconda3/envs/tensorflow/lib/python3.5/site-packages/jedi/cache.py", line 119, in wrapper
    return dct[key]
  File "/home/keisukefujii/anaconda3/envs/tensorflow/lib/python3.5/site-packages/jedi/cache.py", line 46, in wrapper
    return getattr(self, name)
value called
None
AttributeError: 'CompiledName' object has no attribute '_infer'
Traceback (most recent call last):
```

I am using IPython 6.1.0.
If it should be filed in IPython, please let me know.

``

### Output of “:verbose JediDebugInfo”

Sorry, but I just use IPython. If someone gives me a suggestion to do this,
I will add the output.

**Comment by fujiisoup** [comment]
Closed I filed this issue to the wrong repo...
Sorry to bother.
