### ISSUE TITLE
AttributeError: 'DictComprehension' object has no attribute 'exact_key_items'

### ISSUE THREAD

**Issue by mkoura** [davidhalter/jedi-vim#772]
### Issue

Showing usages fails with ``AttributeError: 'DictComprehension' object has no attribute 'exact_key_items'``

### Steps to reproduce

https://github.com/mkoura/dump2polarion/blob/master/dump2polarion/dumper_cli.py#L103
Showing usages on ``response`` leads to the mentioned error.

### Output of “:verbose JediDebugInfo”
```
Using Python version: 2
 - sys.version: `2.7.14 (default, Jan 17 2018, 14:28:32), [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]`
 - site module: `/home/martink/.local/python_venvs/neovim2/lib64/python2.7/site.pyc`
Jedi path: `/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.pyc`
 - version: 0.11.1
 - sys_path:
    - `/home/martink/Source/repos/dump2polarion`
    - `/home/martink/.local/python_venvs/dump2polarion/lib/python2.7/site-packages`
    - `/home/martink/Source/repos/dump2polarion`
    - `/home/martink/.local/python_venvs/dump2polarion/lib/python2.7/site-packages/_pdbpp_path_hack`
    - `/home/martink/.local/python_venvs/neovim2/lib/python27.zip`
    - `/home/martink/.local/python_venvs/neovim2/lib64/python2.7`
    - `/home/martink/.local/python_venvs/neovim2/lib64/python2.7/plat-linux2`
    - `/home/martink/.local/python_venvs/neovim2/lib64/python2.7/lib-tk`
    - `/home/martink/.local/python_venvs/neovim2/lib64/python2.7/lib-old`
    - `/home/martink/.local/python_venvs/neovim2/lib64/python2.7/lib-dynload`
    - `/usr/lib64/python2.7`
    - `/usr/lib/python2.7`
    - `/usr/lib64/python2.7/lib-tk`
    - `/home/martink/.local/python_venvs/neovim2/lib/python2.7/site-packages`
    - `_vim_path_`
 - jedi-vim git version: 510b1c9-dirty
 - jedi git submodule status:  02f238ce08f2d7f9c4af9a17cbf5754836775e2f pythonx/jedi (v0.11.1)
 2ca629a2f6db2e905ddd5188113b1045f8a00fc2 pythonx/parso (v0.1.1)
```

#### :version
```
NVIM v0.2.2
Build type: RelWithDebInfo
Lua 5.3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-
switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -
DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-
color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.2.2/build/config -I/builddir/build/BUILD/neovim-0.2.2/src -I/usr/include -I/us
r/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/builddir/build/BUILD/neovim-0.2.2/build/src/nvim/auto -I/builddir/build/BUILD/neo
vim-0.2.2/build/include
Compiled by mockbuild

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
### Traceback
```
Traceback (most recent call last):
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi_vim.py", line 131, in wrapper
    return func(*args, **kwargs)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi_vim.py", line 247, in goto
    definitions = script.usages()
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 244, in usages
    names = usages.usages(self._get_module(), tree_name)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/usages.py", line 47, in usages
    new = _find_names(m, name_leaf)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/usages.py", line 33, in _find_names
    found_names = set(name.goto())
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/filters.py", line 57, in goto
    return self.parent_context.evaluator.goto(self.parent_context, self.tree_name)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 294, in goto
    search_global=True, is_goto=True
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/_compatibility.py", line 204, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/base_context.py", line 139, in py__getattribute__
    return f.filter_name(filters)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/finder.py", line 121, in filter_name
    names = filter.get(self._string_name)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/filters.py", line 170, in get
    return self._convert_names(self._filter(names))
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/filters.py", line 202, in _filter
    return list(self._check_flows(names))
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/filters.py", line 216, in _check_flows
    self._node_context, self._parser_scope, name, self._origin_scope
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/flow_analysis.py", line 76, in reachability_check
    return _break_check(context, context_scope, first_flow_scope, node)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/flow_analysis.py", line 91, in _break_check
    reachable = _check_if(context, flow_node)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/flow_analysis.py", line 107, in _check_if
    types = context.eval_node(node)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/base_context.py", line 123, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 174, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 191, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/__init__.py", line 195, in _eval_element_cached
    return eval_node(context, element)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/finder.py", line 64, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/finder.py", line 157, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/finder.py", line 157, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/filters.py", line 118, in infer
    return self.get_param().infer()
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/filters.py", line 121, in get_param
    params = self.parent_context.get_params()
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/context/function.py", line 226, in get_params
    return self.var_args.get_params(self)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/arguments.py", line 79, in get_params
    execution_context.tree_node
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/dynamic.py", line 87, in search_params
    for function_execution in function_executions
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/dynamic.py", line 87, in <genexpr>
    for function_execution in function_executions
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/context/function.py", line 226, in get_params
    return self.var_args.get_params(self)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/arguments.py", line 70, in get_params
    return get_params(execution_context, self)
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/param.py", line 52, in get_params
    unpacked_va = list(var_args.unpack(funcdef))
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/arguments.py", line 139, in unpack
    for key, values in _star_star_dict(self.context, dct, el, funcdef):
  File "/home/martink/.local/share/nvim/plugged/jedi-vim/pythonx/jedi/jedi/evaluate/arguments.py", line 239, in _star_star_dict
    return array.exact_key_items()
AttributeError: 'DictComprehension' object has no attribute 'exact_key_items'
```

**Comment by davidhalter** [comment]
Jedi has changed a lot. Please upgrade jedi-vim to latest and recheck if this is still an issue. I assume it's not, but please check.

**Comment by davidhalter** [comment]
Closing. Let me know if this issue still occurs. If it does I will reopen.
