### ISSUE TITLE
Cannot follow relative imports

### ISSUE THREAD

**Issue by IamGianluca** [davidhalter/jedi-vim#788]
Hi,

I'm working on a project that uses `pytorch`. While working on it, I've noticed that that `jedi-vim` is not able to follow relative imports when using the `<Leader>-g` shortcut to go to definition. 

In my case, I'm not able to jump to the definition of the `Linear` class in `pytorch`, which is imported in the `torch/lib/python3.6/site-packages/torch/nn/modules/__init__.py` file as:

```
from .linear import Linear, Bilinear
```

If I position the curson over `Linear` and press `<Leader>-g`, I get the following error message:

```
jedi-vim: Couldn't find any definitions for this.
```

**Comment by davidhalter** [comment]
Hi Gianluca

Please try jedi's master branch. I'm pretty positive that this was fixed.

~ Dave

**Comment by IamGianluca** [comment]
Hi David,

I'm using the latest commit from master (`48af2af`). Is there anything else I can do to help narrow down the bug?

**Comment by davidhalter** [comment]
You're using latest jedi-vim. jedi-vim still uses jedi 0.11.1. jedi 0.12.0 is not out yet, but the bug is already fixed on jedi's master.

**Comment by IamGianluca** [comment]
I see, thanks for the clarification @davidhalter. I really appreciate it!

Do you have any idea when `jedi-vim` will use latest `jedi`? As far as I know I cannot do much right now to force `jedi-vim` to use the more recent version of `jedi` ― I've tried to install the most recent committed version of `jedi`(commit: `e6a3a88`) but `jedi-vim` is still returning the error message, which makes me think it's not sufficient that I install the newest `jedi` on my system.

**Comment by davidhalter** [comment]
I'm pretty sure that there's something wrong with your setup. Can you run `:JediDebugInfo`? I know it will probably fail half way through, but the start of the script is still interesting.

**Comment by IamGianluca** [comment]
I see. Let me know if I can do anything else to help  @davidhalter 

```
#### Jedi-vim debug information                                                                                                                                                 
Using Python version: 3                                                                                                                                                         
 - sys.version: `3.6.3 (default, Nov 29 2017, 16:33:28), [GCC 5.4.0 20160609]`                                                                                                  
 - site module: `/home/gianluca/.pyenv/versions/search/lib/python3.6/site.py`                                                                                                   
Jedi path: `/home/gianluca/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`                                                                                                 
 - version: 0.11.1                                                                                                                                                              
 - sys_path:                                                                                                                                                                    
    - `/home/gianluca/git/myproject/api`                                                                                                                                       
    - `/home/gianluca/git/myproject/celery_workers`                                                                                                                            
    - `/home/gianluca/git/myproject/utils`                                                                                                                                     
    - `/home/gianluca/git/myproject/data_handlers`                                                                                                                             
    - `/home/gianluca/.pyenv/versions/3.6.3/envs/search/src/jedi`                                                                                                               
    - `/home/gianluca/git/myproject/automated_tests`                                                                                                                           
    - `/home/gianluca/.pyenv/versions/3.6.3/envs/search/lib/python3.6/site-packages`                                                                                            
    - `/home/gianluca/git/myproject/api`                                                                                                                                       
    - `/home/gianluca/git/myproject/celery_workers`                                                                                                                            
    - `/home/gianluca/git/myproject/automated_tests`                                                                                                                           
    - `/home/gianluca/git/myproject/data_handlers`                                                                                                                             
    - `/home/gianluca/git/myproject/utils`                                                                                                                                     
    - `/home/gianluca/.pyenv/versions/3.6.3/envs/search/src/jedi`                                                                                                               
    - `/home/gianluca/.pyenv/versions/search/lib/python36.zip`                                                                                                                  
    - `/home/gianluca/.pyenv/versions/search/lib/python3.6`                                                                                                                     
    - `/home/gianluca/.pyenv/versions/search/lib/python3.6/lib-dynload`                                                                                                         
    - `/home/gianluca/.pyenv/versions/3.6.3/lib/python3.6`                                                                                                                      
    - `/home/gianluca/.pyenv/versions/search/lib/python3.6/site-packages`                                                                                                       
    - `/home/gianluca/git/myproject/api`                                                                                                                                       
    - `/home/gianluca/git/myproject/celery_workers`                                                                                                                            
    - `/home/gianluca/git/myproject/automated_tests`                                                                                                                           
    - `/home/gianluca/git/myproject/data_handlers`                                                                                                                             
    - `/home/gianluca/git/myproject/utils`                                                                                                                                     
    - `/home/gianluca/.pyenv/versions/3.6.3/envs/search/src/jedi`                                                                                                               
    - `_vim_path_`                                                                                                                                                              
 - jedi-vim git version: 48af2af                                                                                                                                                
 - jedi git submodule status:  02f238ce08f2d7f9c4af9a17cbf5754836775e2f pythonx/jedi (v0.11.1)                                                                                  
 2ca629a2f6db2e905ddd5188113b1045f8a00fc2 pythonx/parso (v0.1.1)                                                                                                                
                                                                                                                                                                                
##### Settings                                                                                                                                                                  
                                                                                                                                                                             
g:jedi#completions_enabled = 0 (default: 1)                                                                                                                                     
                                                                                                                                                                                
  omnifunc=                                                                                                                                                                     
  completeopt=menuone,longest,preview                                                                                                                                           
        Last set from ~/.vim/plugged/jedi-vim/plugin/jedi.vim                                                                                                                   
                                                  

```

**Comment by davidhalter** [comment]
You obviously haven't updated jedi in the right place ;-) If you did the update in a correct way, there would be a version 0.12.0.

Jedi lives inside: /home/gianluca/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py

**Comment by IamGianluca** [comment]
I'm a bit confused. As you can see from the log I posted I'm using `pyenv` to manage python virtualenvs. I thought I should have `pip` installed the latest version of `jedi` within the Python virtual environment through a `pip install -e git://github.com/davidhalter/jedi.git@e6a3a8882c1e3469c36c691e11b288fe4b709ecf#egg=jedi`.  Unfortunately, that doesn't work. 

I've also tried to install the latest version of `jedi` on my system environment, but of course that doesn't work either when I'm using `neovim` inside a virtual env.

Lastly, I've tried to install `jedi` through `vim-plug`, but also that didn't work for me.

Am I doing something wrong?

**Comment by davidhalter** [comment]
> Am I doing something wrong?

Yes. :)

Goto `/home/gianluca/.vim/plugged/jedi-vim/pythonx/jedi` and type `git pull<enter>` :) It's a submodule. It's not supposed to be updated by the system, it's controlled by jedi-vim.

It's also not an official release, so some things will fail. I will probably release it in a month or so.

**Comment by IamGianluca** [comment]
Thank you @davidhalter ! It's working now :-)

**Comment by alwc** [comment]
I have the same problem with Gianluca, so I followed your instruction and did a git pull. However, after the pull I can't even go to my imported libraries. 

When I type `:JediDebugInfo` in neovim, I got the following error

```
#### Jedi-vim debug information
Using Python version: 3
 - sys.version: `3.6.5 (default, Apr 17 2018, 18:20:05), [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]`
 - site module: `/Users/alwc/.pyenv/versions/3.6.5/lib/python3.6/site.py`
Jedi path: `/Users/alwc/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.12.0
 - sys_path:
Error detected while processing function jedi#debug_info[28]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "/Users/alwc/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 37, in display_debug_info
    sys_path = script_evaluator.project.sys_path
AttributeError: 'Project' object has no attribute 'sys_path'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/alwc/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 39, in display_debug_info
    sys_path = script_evaluator.sys_path
AttributeError: 'Evaluator' object has no attribute 'sys_path'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/alwc/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 44, in display_debug_info
    "{0!r})".format(e))
  File "/Users/alwc/dotfiles/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 8, in echo
    vim.command('echo {0}'.format(msg))
  File "/Users/alwc/.pyenv/versions/neovim3/lib/python3.6/site-packages/neovim/api/nvim.py", line 242, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/alwc/.pyenv/versions/neovim3/lib/python3.6/site-packages/neovim/api/nvim.py", line 140, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/alwc/.pyenv/versions/neovim3/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim(echo):E117: Unknown function: AttributeError'
Error detected while processing function jedi#debug_info:
line   28:
E171: Missing :endif
```

**Comment by davidhalter** [comment]
Use the virtualenv branch. It's currently a pull request and waiting to be merged.
