### ISSUE TITLE
JediDebugInfo raise AttributeError: 'Evaluator' object has no attribute 'sys_path' 

### ISSUE THREAD

**Issue by bstaint** [davidhalter/jedi-vim#795]
### Issue

run JediDebugInfo will raise:
```
Traceback (most recent call last):
  File "D:\Portable\gVim\vimfiles\bundle\jedi-vim\pythonx\jedi_vim_debug.py", line 37, in display_debug_info
    sys_path = script_evaluator.project.sys_path
AttributeError: 'Project' object has no attribute 'sys_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Portable\gVim\vimfiles\bundle\jedi-vim\pythonx\jedi_vim_debug.py", line 39, in display_debug_info
    sys_path = script_evaluator.sys_path
AttributeError: 'Evaluator' object has no attribute 'sys_path'
```

### Steps to reproduce

run JediDebugInfo

**Comment by davidhalter** [comment]
Start using the virtualenv branch, I'll be fixing some of these things in the next few days.

**Comment by davidhalter** [comment]
Fixed in the virtualenv branch.
