### ISSUE TITLE
JediDebugInfo not working correctly

### ISSUE THREAD

**Issue by min6434** [davidhalter/jedi-vim#826]
### Issue

When I use command :JediDebugInfo, I see an error below
> 
> line   28:
> Traceback (most recent call last):
>   File "/home/min6434/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 37, in display_debug_info
>     sys_path = script_evaluator.project.sys_path
> AttributeError: 'Project' object has no attribute 'sys_path'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "/home/min6434/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 39, in display_debug_info
>     sys_path = script_evaluator.sys_path
> AttributeError: 'Evaluator' object has no attribute 'sys_path'
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/min6434/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 44, in display_debug_info
>     "{0!r})".format(e))
>   File "/home/min6434/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 8, in echo
>     vim.command('echo {0}'.format(msg))
> vim.error: Vim(echo):E117: Unknown function: AttributeError
> E171: Missing :endif
> 

So I changed jedi_vim/pythonx/jedi_vim_debug.py files to correct the error
from this 
```
            script_evaluator = jedi_vim.jedi.Script('')._evaluator
            try:
                sys_path = script_evaluator.project.sys_path
            except AttributeError:
                **sys_path = script_evaluator.sys_path**
```
to this
```
            script_evaluator = jedi_vim.jedi.Script('')._evaluator
            try:
                sys_path = script_evaluator.project.sys_path
            except AttributeError:
                **sys_path = script_evaluator.get_sys_path()**
```
Then I could get the result.

I don't know it is a bug or something are wrong in my set-up.

### Steps to reproduce
In the vim type ':JediDebugInfo'.

### Output of “:verbose JediDebugInfo”

When I corrected the python script I get this result 
> #### Jedi-vim debug information
> Using Python version: 3
>  - sys.version: `3.5.2 (default, Nov 23 2017, 16:37:01), [GCC 5.4.0 20160609]`
>  - site module: `/usr/lib/python3.5/site.py`
> Jedi path: `/home/min6434/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
>  - version: 0.12.0
>  - sys_path:
>     - `/home/min6434/Documents/PYTHON/camelyon`
>     - `/home/min6434/Documents/PYTHON/camelyon/opt/ASAP/bin`
>     - `/home/min6434/anaconda3/lib/python36.zip`
>     - `/home/min6434/anaconda3/lib/python3.6`
>     - `/home/min6434/anaconda3/lib/python3.6/lib-dynload`
>     - `/home/min6434/anaconda3/lib/python3.6/site-packages`
>     - `/home/min6434/anaconda3/lib/python3.6/site-packages/Sphinx-1.6.3-py3.6.egg`
>  - jedi-vim git version: 0.9.0-6-g7894b38-dirty
>  - jedi git submodule status:  bd7c65d9639c2d451d44c6d135b4f6043a918950 pythonx/jedi (v0.12.0)
>  579146b5010ae22aa0a32c6098413189baa4367d pythonx/parso (v0.2.0)
> 
> ##### Settings
> ```
> g:jedi#use_splits_not_buffers = 'right' (default: 1)
> 
>   omnifunc=jedi#completions
>         Last set from ~/.vim/bundle/jedi-vim/autoload/jedi.vim
>   completeopt=menuone,longest,preview
>         Last set from ~/.vim/bundle/jedi-vim/plugin/jedi.vim
> ```

**Comment by min6434** [comment]
Sorry I updated the plugin and the error is gone.
