### ISSUE TITLE
Jedi-vim crash at startup: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by j5shi** [davidhalter/jedi-vim#866]
### Issue

Jedi-vim crash at startup.

crash info:
```
Error detected while processing function jedi#init_python[4]..<SNR>171_init_python[27]..jedi#setup_python_imports:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 5, in <module>
    from jedi_vim import PythonToVimStr
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
    import jedi
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 19, in <module>
    from jedi.parser_utils import get_executable_nodes
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/parser_utils.py", line 9
    _EXECUTE_NODES = {'funcdef', 'classdef', 'import_from', 'import_name', 'test',
                               ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 5, in <module>
    from jedi_vim import PythonToVimStr
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
    import jedi
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 19, in <module>
    from jedi.parser_utils import get_executable_nodes
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/parser_utils.py", line 9
    _EXECUTE_NODES = {'funcdef', 'classdef', 'import_from', 'import_name', 'test',
                               ^
SyntaxError: invalid syntax
Error detected while processing function jedi#clear_cache:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'jedi_vim' is not defined

```
### Steps to reproduce

1. Update jedi-vim (from ? don't know) to version (88502891bafda3be9c6c42166d1087c383f65814).
2. Open any python script.
3. Jedi-vim will crash.

there's no issue with my vimrc, same vimrc is being used in a Windows machine and a linux machine and issue only occurs on the linux machine (redhat 6, x86-64, python 2.7.3) recently after I updated the Jedi-vim.

### Output of “:verbose JediDebugInfo”

```
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 0.9.0-54-g8850289
 - jedi git submodule status:  a79a1fbef57564d031c59f47def20a6d9adf3439 pythonx/jedi (v0.12.1)
 - parso git submodule status:  e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso (v0.3.1)

##### Global Python

Using Python version 2 to access Jedi.
Error detected while processing function <SNR>33_jedi_debug_info[12]..jedi#debug_info:
line   31:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 5, in <module>
    from jedi_vim import PythonToVimStr
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
    import jedi
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 19, in <module>
    from jedi.parser_utils import get_executable_nodes
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/parser_utils.py", line 9
    _EXECUTE_NODES = {'funcdef', 'classdef', 'import_from', 'import_name', 'test',
                               ^
SyntaxError: invalid syntax

```

similar issue had been reported: https://github.com/davidhalter/jedi-vim/issues/829

**Comment by davidhalter** [comment]
What is `:python import sys; print(sys.version_info)`? You might still be running Python 2.6.

**Comment by blueyed** [comment]
@j5shi 
Can you please try the following patch to see if `:JediDebugInfo` handles this better then?

```diff
diff --git i/pythonx/jedi_vim_debug.py w/pythonx/jedi_vim_debug.py
index e550a5b..ac047ce 100644
--- i/pythonx/jedi_vim_debug.py
+++ w/pythonx/jedi_vim_debug.py
@@ -2,10 +2,10 @@
 import sys
 
 import vim
-from jedi_vim import PythonToVimStr
 
 
 def echo(msg):
+    from jedi_vim import PythonToVimStr
     vim.command('echo %r' % PythonToVimStr(msg))
```

**Comment by blueyed** [comment]
@j5shi 
Will not help (it will fail only a bit later then).
But we should fix `JediDebugInfo` to be more robust here.

**Comment by j5shi** [comment]
@davidhalter 

`:python import sys; print(sys.version_info)` output `(2, 6, 6, 'final', 0)`

but when I launch the default python, it's shows

```
Python 2.7.3 (default, Jun 22 2015, 05:48:48)
[GCC 4.4.4 20100726 (Red Hat 4.4.4-13)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

What's hell is wrong with my environment...?

**Comment by j5shi** [comment]
@blueyed 
I made the change as your suggested

```
 pythonx/jedi_vim_debug.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/pythonx/jedi_vim_debug.py b/pythonx/jedi_vim_debug.py
index e550a5b..ac047ce 100644
--- a/pythonx/jedi_vim_debug.py
+++ b/pythonx/jedi_vim_debug.py
@@ -2,10 +2,10 @@
 import sys

 import vim
-from jedi_vim import PythonToVimStr


 def echo(msg):
+    from jedi_vim import PythonToVimStr
     vim.command('echo %r' % PythonToVimStr(msg))
```
output seems is the same as before

```
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 0.9.0-54-g8850289-dirty
 - jedi git submodule status:  a79a1fbef57564d031c59f47def20a6d9adf3439 pythonx/jedi (v0.12.1)
 - parso git submodule status:  e6bc924fbabbfa3090044e475c91a7655b9c6e9b pythonx/parso (v0.3.1)

##### Global Python

Using Python version 2 to access Jedi.
Error detected while processing function <SNR>33_jedi_debug_info[12]..jedi#debug_info:
line   32:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 38, in display_debug_info
    for x in sys.version.split('\n')])))
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim_debug.py", line 8, in echo
    from jedi_vim import PythonToVimStr
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
    import jedi
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 19, in <module>
    from jedi.parser_utils import get_executable_nodes
  File "/home/j5shi/.vim/bundle/jedi-vim/pythonx/jedi/jedi/parser_utils.py", line 9
    _EXECUTE_NODES = {'funcdef', 'classdef', 'import_from', 'import_name', 'test',
                               ^
SyntaxError: invalid syntax
```

**Comment by j5shi** [comment]
@blueyed 

```
:version
VIM - Vi IMproved 8.1 (2018 May 17, compiled Jun 20 2018 16:47:44)
Included patches: 1-89
Compiled by j5shi.vip@gmail.com
Huge version without GUI.  Features included (+) or not (-):
+acl               -clientserver      +dialog_con        +find_in_path      +keymap            +modify_fname      +multi_byte        +profile           +statusline        +textobjects       +wildignore
+arabic            -clipboard         +diff              +float             +lambda            +mouse             +multi_lang        +python            -sun_workshop      +timers            +wildmenu
+autocmd           +cmdline_compl     +digraphs          +folding           +langmap           -mouseshape        -mzscheme          -python3           +syntax            +title             +windows
-autoservername    +cmdline_hist      -dnd               -footer            +libcall           +mouse_dec         +netbeans_intg     +quickfix          +tag_binary        -toolbar           +writebackup
-balloon_eval      +cmdline_info      -ebcdic            +fork()            +linebreak         -mouse_gpm         +num64             +reltime           +tag_old_static    +user_commands     -X11
+balloon_eval_term +comments          +emacs_tags        +gettext           +lispindent        -mouse_jsbterm     +packages          +rightleft         -tag_any_white     +vertsplit         -xfontset
-browse            +conceal           +eval              -hangul_input      +listcmds          +mouse_netterm     +path_extra        -ruby              -tcl               +virtualedit       -xim
++builtin_terms    +cryptv            +ex_extra          +iconv             +localmap          +mouse_sgr         -perl              +scrollbind        +termguicolors     +visual            -xpm
+byte_offset       +cscope            +extra_search      +insert_expand     +lua               -mouse_sysmouse    +persistent_undo   +signs             +terminal          +visualextra       -xsmp
+channel           +cursorbind        +farsi             +job               +menu              +mouse_urxvt       +postscript        +smartindent       +terminfo          +viminfo           -xterm_clipboard
+cindent           +cursorshape       +file_in_path      +jumplist          +mksession         +mouse_xterm       +printer           +startuptime       +termresponse      +vreplace          -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
 f-b for $VIMRUNTIME: "/home/j5shi/vim81/usr/local/share/vim/vim81"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE    -lm -ltinfo -lnsl  -lselinux   -L/usr/local/lib -llua  -L/usr/lib64/python2.6/config -lpython2.6 -lpthread -ldl -lutil -lm -Xlinke
r -export-dynamic

```

**Comment by j5shi** [comment]
ah...seems it linked python 2.6... will try to re-compile vim...and will let you guys know the result. Thanks a ton.

**Comment by davidhalter** [comment]
I'll close this one, because Python 2.6 is not supported anymore. Sorry!

**Comment by j5shi** [comment]
F.Y.I.
After re-compiled vim and force it to link against python 2.7, problem fixed, thanks @davidhalter and @blueyed.

```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug  2 2018 16:59:08)
Included patches: 1-233
Compiled by j5shi.vip@gmail.com
Huge version without GUI.  Features included (+) or not (-):
+acl               -clientserver      +diff              +folding           +libcall           -mouse_gpm         +packages          -ruby              +termguicolors     +visual            -xsmp
+arabic            -clipboard         +digraphs          -footer            +linebreak         -mouse_jsbterm     +path_extra        +scrollbind        +terminal          +visualextra       -xterm_clipboard
+autocmd           +cmdline_compl     -dnd               +fork()            +lispindent        +mouse_netterm     -perl              +signs             +terminfo          +viminfo           -xterm_save
+autochdir         +cmdline_hist      -ebcdic            +gettext           +listcmds          +mouse_sgr         +persistent_undo   +smartindent       +termresponse      +vreplace
-autoservername    +cmdline_info      +emacs_tags        -hangul_input      +localmap          -mouse_sysmouse    +postscript        +startuptime       +textobjects       +wildignore
-balloon_eval      +comments          +eval              +iconv             +lua               +mouse_urxvt       +printer           +statusline        +timers            +wildmenu
+balloon_eval_term +conceal           +ex_extra          +insert_expand     +menu              +mouse_xterm       +profile           -sun_workshop      +title             +windows
-browse            +cryptv            +extra_search      +job               +mksession         +multi_byte        +python            +syntax            -toolbar           +writebackup
++builtin_terms    +cscope            +farsi             +jumplist          +modify_fname      +multi_lang        -python3           +tag_binary        +user_commands     -X11
+byte_offset       +cursorbind        +file_in_path      +keymap            +mouse             -mzscheme          +quickfix          +tag_old_static    +vartabs           -xfontset
+channel           +cursorshape       +find_in_path      +lambda            -mouseshape        +netbeans_intg     +reltime           -tag_any_white     +vertsplit         -xim
+cindent           +dialog_con        +float             +langmap           +mouse_dec         +num64             +rightleft         -tcl               +virtualedit       -xpm
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
 f-b for $VIMRUNTIME: "/home/j5shi/vim81/usr/local/share/vim/vim81"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE    -lm -ltinfo -lnsl  -lselinux   -L/usr/local/lib -llua  -L/home/j5shi/proj/python27/root/usr/lib64/python2.7/config -lpython2.7 -lp
thread -ldl -lutil -lm -Xlinker -export-dynamic
```
