### ISSUE TITLE
jedi-vim does not initialises

### ISSUE THREAD

**Issue by anudeepsamaiya** [davidhalter/jedi-vim#893]
### Issue
ImportError: No module named jedi_vim_debug

```
"settings.py" 1014L, 33013C
Error detected while processing function jedi#init_python[4]..<SNR>45_init_python[27]..jedi#setup_python_imports:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
ImportError: No module named jedi_vim_debug
```

### Steps to reproduce
Open vim in python2.7 environment

### Output of “:verbose JediDebugInfo”
```
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 0.9.0-62-g7f4f2db
 - jedi git submodule status:  bd1010bbd2693f189ff780eb21fc4294071cb280 pythonx/jedi (v0.13.1)
 - parso git submodule status:  930ec08ab0cd77aae07e24aa78f9c5119be216bb pythonx/parso (v0.3.1-7-g930ec08)

##### Global Python

Using Python version 2 to access Jedi.
Error detected while processing function <SNR>18_jedi_debug_info[12]..jedi#debug_info:
line   31:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jedi_vim_debug
```

**Comment by blueyed** [comment]
I assume this is solved, since you posted another issue already?
Otherwise this is due to a broken setup in some way.
See also https://github.com/davidhalter/jedi-vim/issues/875 - but no real solution there also.

Please follow up if you remember what the issue was.
