### ISSUE TITLE
Failed to initialize Python imports

### ISSUE THREAD

**Issue by artem0** [davidhalter/jedi-vim#916]
### Issue

During an attempt to run vim with jedi-vim plugin initialization errors were thrown. I have tried to install jedi-vim from source with git and with using pathogen. In both cases, I faced the same errors.

### Output of “:verbose JediDebugInfo”

```
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 1f7e661
 - jedi git submodule status:  0bf8a69024aff8599bd1f323c4feba2703ef3d59 pythonx/jedi (v0.13.3)
 - parso git submodule status:  acccb4f28d6d57f4ad4c882f3408136ee8f50ff5 pythonx/parso (v0.3.4)

##### Global Python

Using Python version 2 to access Jedi.
Error detected while processing function <SNR>53_jedi_debug_info[12]..jedi#debug_info:
line   31:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/artem/.vim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 5, in <module>
    from jedi_vim import PythonToVimStr
  File "/Users/artem/.vim/plugged/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
    import jedi
  File "/Users/artem/.vim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/Users/artem/.vim/plugged/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 21, in <module>
    from jedi import debug
  File "/Users/artem/.vim/plugged/jedi-vim/pythonx/jedi/jedi/debug.py", line 23, in <module>
    from colorama import Fore, init
  File "/Users/artem/Library/Python/2.7/lib/python/site-packages/colorama/__init__.py", line 2, in <module>
    from .initialise import init, deinit, reinit, colorama_text
  File "/Users/artem/Library/Python/2.7/lib/python/site-packages/colorama/initialise.py", line 6, in <module>
    from .ansitowin32 import AnsiToWin32
  File "/Users/artem/Library/Python/2.7/lib/python/site-packages/colorama/ansitowin32.py", line 7, in <module>
    from .winterm import WinTerm, WinColor, WinStyle
  File "/Users/artem/Library/Python/2.7/lib/python/site-packages/colorama/winterm.py", line 2, in <module>
    from . import win32
  File "/Users/artem/Library/Python/2.7/lib/python/site-packages/colorama/win32.py", line 8, in <module>
    import ctypes
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
```

The whole error log is provided above (I have the same stacktrace during launching vim).

**Comment by davidhalter** [comment]
Can you uninstall colorama and recheck? Something is probably wrong with your Python or system, because it's not possible to import ctypes.

**Comment by artem0** [comment]
@davidhalter Thanks for the swift response. Removing `colorama` solved my issue. Have no idea why this package could be a root cause of my problem 🤷‍♂️. We can close this issue.
