### ISSUE TITLE
auto-competion item become half when the function paramenter hide a of of definition of that item

### ISSUE THREAD

**Issue by evan0greenup** [davidhalter/jedi-vim#923]
### Steps to reproduce

Expected
```python3
func=lamda x: x*3

hello_today_and_tomorrow="hello"
#* |   (x)   |
func(hello_today_and_tomorrow)
                           |  hello_today_and_tomorrow  |
```

Actual
```python3
func=lambda x:x*3

hel#*|  (x)  | ...
func(hel
#*     | hel  |
```

**NOTE**: the area commented by #* is ui component.

### Output of “:verbose JediDebugInfo”

```python3
#### Jedi-vim debug information
Using Python version: 3
 - sys.version: `3.7.2 (default, Jan 10 2019, 23:51:51), [GCC 8.2.1 20181127]`
 - site module: `/usr/lib/python3.7/site.py`
Jedi path: `/usr/lib/python3.7/site-packages/jedi/__init__.py`
 - version: 0.13.3
 - sys_path:
Error detected while processing function jedi#debug_info:
line   28:
Traceback (most recent call last):
  File "/usr/share/vim/vimfiles/pythonx/jedi_vim_debug.py", line 37, in display_debug_info
    sys_path = script_evaluator.project.sys_path
AttributeError: 'Project' object has no attribute 'sys_path'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/vim/vimfiles/pythonx/jedi_vim_debug.py", line 39, in display_debug_info
    sys_path = script_evaluator.sys_path
AttributeError: 'Evaluator' object has no attribute 'sys_path'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/vim/vimfiles/pythonx/jedi_vim_debug.py", line 44, in display_debug_info
    "{0!r})".format(e))
  File "/usr/share/vim/vimfiles/pythonx/jedi_vim_debug.py", line 8, in echo
    vim.command('echo {0}'.format(msg))
vim.error: Vim(echo):E117: Unknown function: AttributeError
E171: Missing :endif

```

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.

**Comment by evan0greenup** [comment]
@davidhalter , the debug info added, hope to reopen the issue.

**Comment by davidhalter** [comment]
Can you upgrade jedi-vim to latest master? I feel like at least the debugging info would work then.
