### ISSUE TITLE
jedi-vim not working (possibly issue with conda)

### ISSUE THREAD

**Issue by tomchor** [davidhalter/jedi-vim#929]
### Issue

After I install `jedi-vim` using `vundle` (with no errors) I get errors when opening python files and `jedi-vim` doesn't work. I've checked a few issues with similar errors but I still couldn't debug this.

### Steps to reproduce

1 - Install `jedi-vim` using `vundle`
2 - `pip install jedi`
3 - open python file

### Output of “:verbose JediDebugInfo”

 verbose JediDebugInfo
##### jedi-vim version

 - jedi-vim git version: 0.9.0-74-g69aa410
 - jedi git submodule status:  0bf8a69024aff8599bd1f323c4feba2703ef3d59 pythonx/jedi (v0.13.3)

##### jedi-vim version

 - jedi-vim git version: 0.9.0-74-g69aa410
 - jedi git submodule status:  0bf8a69024aff8599bd1f323c4feba2703ef3d59 pythonx/jedi (v0.13.3)
 - parso git submodule status:  acccb4f28d6d57f4ad4c882f3408136ee8f50ff5 pythonx/parso (v0.3.4)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.3 (default, Mar 26 2019, 21:43:19), [GCC 8.2.1 20181127]`
 - global site module: `/home/tomas/miniconda3/lib/python3.7/site.py`
ERROR: could not import the "jedi" Python module: ImportError: /home/tomas/miniconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined s
ymbol: _Py_write_noraise
  Traceback (most recent call last):
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
      from parso.parser import ParserSyntaxError
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 26, in <module>
      from parso import tree
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/tree.py", line 3, in <module>
      from parso._compatibility import utf8_repr, encoding, py_version
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/_compatibility.py", line 6, in <module>
      import platform
    File "/home/tomas/miniconda3/lib/python3.7/platform.py", line 116, in <module>
      import sys, os, re, subprocess
    File "/home/tomas/miniconda3/lib/python3.7/subprocess.py", line 152, in <module>
      import _posixsubprocess

##### Settings

```
  omnifunc=python3complete#Complete
  completeopt=menuone,longest,preview
        Last set from ~/.vim/bundle/jedi-vim/plugin/jedi.vim line 31
```

#### :version
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 26 2019 21:55:55)
Included patches: 1-1186
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     +emacs_tags        +insert_expand     +modify_fname      +netbeans_intg     +ruby/dyn          +terminfo          +vreplace
+arabic            +cmdline_hist      +eval              +job               +mouse             +num64             +scrollbind        +termresponse      +wildignore
+autocmd           +cmdline_info      +ex_extra          +jumplist          -mouseshape        +packages          +signs             +textobjects       +wildmenu
+autochdir         +comments          +extra_search      +keymap            +mouse_dec         +path_extra        +smartindent       +textprop          +windows
-autoservername    +conceal           -farsi             +lambda            +mouse_gpm         +perl/dyn          +startuptime       +timers            +writebackup
-balloon_eval      +cryptv            +file_in_path      +langmap           -mouse_jsbterm     +persistent_undo   +statusline        +title             -X11
+balloon_eval_term +cscope            +find_in_path      +libcall           +mouse_netterm     +postscript        -sun_workshop      -toolbar           -xfontset
-browse            +cursorbind        +float             +linebreak         +mouse_sgr         +printer           +syntax            +user_commands     -xim
++builtin_terms    +cursorshape       +folding           +lispindent        -mouse_sysmouse    +profile           +tag_binary        +vartabs           -xpm
+byte_offset       +dialog_con        -footer            +listcmds          +mouse_urxvt       +python/dyn        -tag_old_static    +vertsplit         -xsmp
+channel           +diff              +fork()            +localmap          +mouse_xterm       +python3/dyn       -tag_any_white     +virtualedit       -xterm_clipboard
+cindent           +digraphs          +gettext           +lua/dyn           +multi_byte        +quickfix          +tcl/dyn           +visual            -xterm_save
-clientserver      -dnd               -hangul_input      +menu              +multi_lang        +reltime           +termguicolors     +visualextra
-clipboard         -ebcdic            +iconv             +mksession         -mzscheme          +rightleft         +terminal          +viminfo
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.28/core_perl/C
ORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,
/usr/lib/perl5/5.28/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.28/core_perl/CORE -lperl -
lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"Ra_rbc2.py" 150L, 5022C
jedi-vim error: jedi#setup_python_imports: ImportError: /home/tomas/miniconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: 
_Py_write_noraise
  Traceback (most recent call last):
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
      from parso.parser import ParserSyntaxError
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 26, in <module>
      from parso import tree
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/tree.py", line 3, in <module>
      from parso._compatibility import utf8_repr, encoding, py_version
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/_compatibility.py", line 6, in <module>
      import platform
    File "/home/tomas/miniconda3/lib/python3.7/platform.py", line 116, in <module>
      import sys, os, re, subprocess
    File "/home/tomas/miniconda3/lib/python3.7/subprocess.py", line 152, in <module>
      import _posixsubprocess
Error detected while processing function jedi#init_python[11]..<SNR>35_display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: /home/tomas/miniconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-lin
ux-gnu.so: undefined symbol: _Py_write_noraise (in function jedi#init_python[4]..<SNR>35_init_python[27]..jedi#setup_python_imports, line 27). See :messages and/or :JediDebu
gInfo for more information.
jedi-vim error: jedi#setup_python_imports: ImportError: /home/tomas/miniconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: 
_Py_write_noraise
  Traceback (most recent call last):
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 41, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
      from parso.parser import ParserSyntaxError
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 26, in <module>
      from parso import tree
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/tree.py", line 3, in <module>
      from parso._compatibility import utf8_repr, encoding, py_version
    File "/home/tomas/.vim/bundle/jedi-vim/pythonx/parso/parso/_compatibility.py", line 6, in <module>
      import platform
    File "/home/tomas/miniconda3/lib/python3.7/platform.py", line 116, in <module>
      import sys, os, re, subprocess
    File "/home/tomas/miniconda3/lib/python3.7/subprocess.py", line 152, in <module>
      import _posixsubprocess
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: /home/tomas/miniconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-lin
ux-gnu.so: undefined symbol: _Py_write_noraise (in function jedi#init_python[4]..<SNR>35_init_python[27]..jedi#setup_python_imports, line 27). See :messages and/or :JediDebu
gInfo for more information.
E475: Invalid argument: @+>
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 26 2019 21:55:55)
```

<details><summary>:scriptnames</summary>

```
  1: /etc/vimrc
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: ~/.vimrc
  4: /usr/share/vim/vim81/ftoff.vim
  5: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
  6: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
  7: /usr/share/vim/vim81/filetype.vim
  8: ~/.vim/bundle/julia-vim/ftdetect/julia.vim
  9: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
 10: /usr/share/vim/vim81/ftplugin.vim
 11: /usr/share/vim/vim81/indent.vim
 12: /usr/share/vim/vim81/syntax/syntax.vim
 13: /usr/share/vim/vim81/syntax/synload.vim
 14: /usr/share/vim/vim81/syntax/syncolor.vim
 15: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 16: /usr/share/vim/vimfiles/plugin/SyntaxFolds.vim
 17: /usr/share/vim/vimfiles/plugin/filebrowser.vim
 18: /usr/share/vim/vimfiles/plugin/imaps.vim
 19: /usr/share/vim/vimfiles/plugin/remoteOpen.vim
 20: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
 21: /usr/share/vim/vim81/plugin/gzip.vim
 22: /usr/share/vim/vim81/plugin/logiPat.vim
 23: /usr/share/vim/vim81/plugin/manpager.vim
 24: /usr/share/vim/vim81/plugin/matchparen.vim
 25: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 26: /usr/share/vim/vim81/plugin/rrhelper.vim
 27: /usr/share/vim/vim81/plugin/spellfile.vim
 28: /usr/share/vim/vim81/plugin/tarPlugin.vim
 29: /usr/share/vim/vim81/plugin/tohtml.vim
 30: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 31: /usr/share/vim/vim81/plugin/zipPlugin.vim
 32: ~/.vim/bundle/julia-vim/autoload/LaTeXtoUnicode.vim
 33: ~/.vim/bundle/julia-vim/autoload/julia_latex_symbols.vim
 34: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 35: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 36: /usr/share/vim/vim81/ftplugin/python.vim
 37: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 38: /usr/share/vim/vim81/indent/python.vim
 39: /usr/share/vim/vim81/syntax/python.vim
 40: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
```
</details>

**Comment by davidhalter** [comment]
We have had some similar issues before with subprocess not working. Somehow VIM was either broken or Python. I'm not sure anymore, but it's not a jedi-vim issue. Please just reinstall everything properly and try again. This is what most users helped. In your case `:python3 import subprocess` doesn't work, so Jedi won't either.
