### ISSUE TITLE
show_call_signatures shows after <Esc>, i

### ISSUE THREAD

**Issue by diazgilberto** [davidhalter/jedi-vim#930]
### Issue
- NVIM v0.3.4
- MacOS 10.14.4

The method signature doesn't show when you stay in insert mode.

While write code like `requests.get(|)` and the cursor stays inside `()` the signature doesn't show. However, if I `<Esc>` and `i` the signature shows. I'm not sure if that is the desire behavior. 

If you are not using jedi-vim from Git (but e.g. from a distribution's package,
please try it with jedi-vim's Git master, too).

### Steps to reproduce
```
  "------ PLUGIN LIST
  call plug#begin('~/.config/nvim/plugged')
      " Plug 'foo/bar', { 'on': [] }            " Temporarily disable a plugin
      Plug 'editorconfig/editorconfig-vim'
      Plug 'airblade/vim-gitgutter'
      Plug 'junegunn/fzf.vim'
      Plug '/usr/local/opt/fzf'                 " Fuzzy search
      Plug 'w0rp/ale'
      Plug 'davidhalter/jedi-vim'               " Python intellisense
      Plug 'vim-airline/vim-airline'            " Status bar plugin
      Plug 'vim-airline/vim-airline-themes'     " Status bar theme
      Plug 'iCyMind/NeoSolarized'               " Syntax
      Plug 'mattn/emmet-vim'                    " HTML & CSS emmet
      Plug 'scrooloose/nerdtree'                " Sidebar file tree browsing
      Plug 'jiangmiao/auto-pairs'               " Automatic close bracket and quote
  call plug#end()

...

  "------ IDE SPECIFICS
  let g:jedi#show_call_signatures = "1"
```

##### jedi-vim version

 - jedi-vim git version: 69aa410
 - jedi git submodule status:  0bf8a69024aff8599bd1f323c4feba2703ef3d59 pythonx/jedi (v0.13.3)
 - parso git submodule status:  acccb4f28d6d57f4ad4c882f3408136ee8f50ff5 pythonx/parso (v0.3.4)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.3 (default, Apr 23 2019, 22:09:23), [Clang 10.0.1 (clang-1001.0.46.4)]`
 - global site module: `/Users/gdiaz/.pyenv/versions/3.7.3/lib/python3.7/site.py`

##### Jedi

 - path: `/Users/gdiaz/.config/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.13.3

##### Jedi environment: <Environment: 3.7.0 in /Users/gdiaz/.pyenv/versions/3.7.0/envs/click-tutorial>

 - executable: /Users/gdiaz/.pyenv/versions/3.7.0/envs/click-tutorial/bin/python
 - sys_path:
    - `/Users/gdiaz/.pyenv/versions/3.7.0/lib/python37.zip`
    - `/Users/gdiaz/.pyenv/versions/3.7.0/lib/python3.7`
    - `/Users/gdiaz/.pyenv/versions/3.7.0/lib/python3.7/lib-dynload`
    - `/Users/gdiaz/.pyenv/versions/3.7.0/envs/click-tutorial/lib/python3.7/site-packages`

##### Known environments

 - <Environment: 3.7.0 in /Users/gdiaz/.pyenv/versions/3.7.0/envs/click-tutorial> (/Users/gdiaz/.pyenv/versions/3.7.0/envs/click-tutorial/bin/python)

##### Settings

```
  omnifunc=jedi#completions
	Last set from ~/.config/nvim/plugged/jedi-vim/autoload/jedi.vim
  completeopt=menuone,longest,preview
	Last set from ~/.config/nvim/plugged/jedi-vim/autoload/jedi.vim
```

#### :version
```

NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/config -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"

Run :checkhealth for more info
```

#### :messages
```




E37: No write since last change (add ! to override)

E488: Trailing characters
E475: Invalid argument: 
clipboard: error: -2
Error detected while processing function <SNR>19_jedi_debug_info[12]..jedi#debug_info[32]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/gdiaz/.config/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 86, in display_debug_info
    environment.executable,
  File "/Users/gdiaz/.config/nvim/plugged/jedi-vim/pythonx/jedi_vim_debug.py", line 9, in echo
    vim.command('echo %r' % PythonToVimStr(msg))
  File "/Users/gdiaz/.pyenv/versions/neovim3/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)
  File "/Users/gdiaz/.pyenv/versions/neovim3/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/gdiaz/.pyenv/versions/neovim3/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Keyboard interrupt'
```

<details><summary>:scriptnames</summary>

```
  1: ~/.config/nvim/init.vim
  2: ~/.config/nvim/autoload/plug.vim
  3: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/filetype.vim
  4: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/ftplugin.vim
  5: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/indent.vim
  6: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/syntax.vim
  7: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/synload.vim
  8: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/syncolor.vim
  9: ~/.config/nvim/plugged/NeoSolarized/colors/NeoSolarized.vim
 10: ~/.config/nvim/plugged/editorconfig-vim/plugin/editorconfig.vim
 11: ~/.config/nvim/plugged/vim-gitgutter/plugin/gitgutter.vim
 12: ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/utility.vim
 13: ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/highlight.vim
 14: ~/.config/nvim/plugged/fzf.vim/plugin/fzf.vim
 15: /usr/local/Cellar/fzf/0.17.5/plugin/fzf.vim
 16: ~/.config/nvim/plugged/ale/plugin/ale.vim
 17: ~/.config/nvim/plugged/ale/autoload/ale/completion.vim
 18: ~/.config/nvim/plugged/ale/autoload/ale/events.vim
 19: ~/.config/nvim/plugged/jedi-vim/plugin/jedi.vim
 20: ~/.config/nvim/plugged/vim-airline/plugin/airline.vim
 21: ~/.config/nvim/plugged/vim-airline/autoload/airline/init.vim
 22: ~/.config/nvim/plugged/vim-airline/autoload/airline/parts.vim
 23: ~/.config/nvim/plugged/vim-airline/autoload/airline/util.vim
 24: ~/.config/nvim/plugged/vim-airline-themes/plugin/airline-themes.vim
 25: ~/.config/nvim/plugged/emmet-vim/plugin/emmet.vim
 26: ~/.config/nvim/plugged/nerdtree/plugin/NERD_tree.vim
 27: ~/.config/nvim/plugged/nerdtree/autoload/nerdtree.vim
 28: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/path.vim
 29: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/menu_controller.vim
 30: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/menu_item.vim
 31: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/key_map.vim
 32: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/bookmark.vim
 33: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/tree_file_node.vim
 34: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/tree_dir_node.vim
 35: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/opener.vim
 36: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/creator.vim
 37: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/flag_set.vim
 38: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/nerdtree.vim
 39: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/ui.vim
 40: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/event.vim
 41: ~/.config/nvim/plugged/nerdtree/lib/nerdtree/notifier.vim
 42: ~/.config/nvim/plugged/nerdtree/autoload/nerdtree/ui_glue.vim
 43: ~/.config/nvim/plugged/nerdtree/nerdtree_plugin/exec_menuitem.vim
 44: ~/.config/nvim/plugged/nerdtree/nerdtree_plugin/fs_menu.vim
 45: ~/.config/nvim/plugged/nerdtree/nerdtree_plugin/vcs.vim
 46: ~/.config/nvim/plugged/auto-pairs/plugin/auto-pairs.vim
 47: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/gzip.vim
 48: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/health.vim
 49: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/man.vim
 50: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/matchit.vim
 51: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/matchparen.vim
 52: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/netrwPlugin.vim
 53: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/rplugin.vim
 54: ~/.local/share/nvim/rplugin.vim
 55: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/remote/host.vim
 56: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/remote/define.vim
 57: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/shada.vim
 58: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/spellfile.vim
 59: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/tarPlugin.vim
 60: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/tohtml.vim
 61: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/tutor.vim
 62: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/plugin/zipPlugin.vim
 63: ~/.config/nvim/plugged/ale/autoload/ale.vim
 64: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions.vim
 65: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/quickfix.vim
 66: ~/.config/nvim/plugged/vim-airline/autoload/airline.vim
 67: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/netrw.vim
 68: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/term.vim
 69: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/hunks.vim
 70: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/virtualenv.vim
 71: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/ale.vim
 72: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/whitespace.vim
 73: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/wordcount.vim
 74: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/keymap.vim
 75: ~/.config/nvim/plugged/vim-airline/autoload/airline/section.vim
 76: ~/.config/nvim/plugged/vim-airline/autoload/airline/highlighter.vim
 77: ~/.config/nvim/plugged/vim-airline-themes/autoload/airline/themes/solarized.vim
 78: ~/.config/nvim/plugged/vim-airline/autoload/airline/themes.vim
 79: ~/.config/nvim/plugged/vim-airline/autoload/airline/builder.vim
 80: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/default.vim
 81: ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter.vim
 82: ~/.config/nvim/plugged/nerdtree/syntax/nerdtree.vim
 83: ~/.config/nvim/plugged/jedi-vim/ftplugin/python/jedi.vim
 84: ~/.config/nvim/plugged/jedi-vim/autoload/jedi.vim
 85: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/provider/python3.vim
 86: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/provider/pythonx.vim
 87: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/provider.vim
 88: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/ftplugin/python.vim
 89: ~/.config/nvim/plugged/jedi-vim/after/ftplugin/python/jedi.vim
 90: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/indent/python.vim
 91: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/python.vim
 92: ~/.config/nvim/plugged/jedi-vim/after/syntax/python.vim
 93: ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/async.vim
 94: ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/debug.vim
 95: ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/diff.vim
 96: ~/.config/nvim/plugged/ale/autoload/ale/util.vim
 97: ~/.config/nvim/plugged/ale/autoload/ale/linter.vim
 98: ~/.config/nvim/plugged/ale/ale_linters/python/bandit.vim
 99: ~/.config/nvim/plugged/ale/ale_linters/python/flake8.vim
100: ~/.config/nvim/plugged/ale/ale_linters/python/mypy.vim
101: ~/.config/nvim/plugged/ale/ale_linters/python/prospector.vim
102: ~/.config/nvim/plugged/ale/ale_linters/python/pycodestyle.vim
103: ~/.config/nvim/plugged/ale/ale_linters/python/pydocstyle.vim
104: ~/.config/nvim/plugged/ale/ale_linters/python/pyflakes.vim
105: ~/.config/nvim/plugged/ale/ale_linters/python/pylama.vim
106: ~/.config/nvim/plugged/ale/ale_linters/python/pylint.vim
107: ~/.config/nvim/plugged/ale/ale_linters/python/pyls.vim
108: ~/.config/nvim/plugged/ale/ale_linters/python/pyre.vim
109: ~/.config/nvim/plugged/ale/ale_linters/python/vulture.vim
110: ~/.config/nvim/plugged/ale/autoload/ale/engine.vim
111: ~/.config/nvim/plugged/ale/autoload/ale/command.vim
112: ~/.config/nvim/plugged/ale/autoload/ale/python.vim
113: ~/.config/nvim/plugged/ale/autoload/ale/path.vim
114: ~/.config/nvim/plugged/ale/autoload/ale/history.vim
115: ~/.config/nvim/plugged/ale/autoload/ale/sign.vim
116: ~/.config/nvim/plugged/ale/autoload/ale/list.vim
117: ~/.config/nvim/plugged/ale/autoload/ale/highlight.vim
118: ~/.config/nvim/plugged/ale/autoload/ale/cursor.vim
119: ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/hunk.vim
120: ~/.config/nvim/plugged/ale/autoload/ale/statusline.vim
121: ~/.config/nvim/plugged/vim-gitgutter/autoload/gitgutter/sign.vim
122: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/scripts.vim
123: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/ftplugin/rst.vim
124: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/indent/rst.vim
125: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/rst.vim
126: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/vim.vim
127: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/perl.vim
128: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/pod.vim
129: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/sh.vim
130: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/php.vim
131: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/html.vim
132: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/javascript.vim
133: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/vb.vim
134: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/css.vim
135: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/sql.vim
136: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/sqloracle.vim
137: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/java.vim
138: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/cpp.vim
139: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/c.vim
140: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/lisp.vim
141: ~/.config/nvim/plugged/vim-airline/autoload/airline/extensions/wordcount/formatters/default.vim
142: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/RstFold.vim
143: ~/.config/nvim/plugged/ale/ale_linters/rst/alex.vim
144: ~/.config/nvim/plugged/ale/autoload/ale/handlers/alex.vim
145: ~/.config/nvim/plugged/ale/ale_linters/rst/proselint.vim
146: ~/.config/nvim/plugged/ale/ale_linters/rst/redpen.vim
147: ~/.config/nvim/plugged/ale/ale_linters/rst/rstcheck.vim
148: ~/.config/nvim/plugged/ale/ale_linters/rst/textlint.vim
149: ~/.config/nvim/plugged/ale/ale_linters/rst/vale.vim
150: ~/.config/nvim/plugged/ale/ale_linters/rst/writegood.vim
151: ~/.config/nvim/plugged/ale/autoload/ale/handlers/writegood.vim
152: ~/.config/nvim/plugged/ale/autoload/ale/handlers/textlint.vim
153: ~/.config/nvim/plugged/ale/autoload/ale/node.vim
154: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/autoload/provider/clipboard.vim
155: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/ftplugin/help.vim
156: /usr/local/Cellar/neovim/0.3.4/share/nvim/runtime/syntax/help.vim
157: ~/.config/nvim/plugged/ale/ale_linters/help/alex.vim
158: ~/.config/nvim/plugged/ale/ale_linters/help/proselint.vim
159: ~/.config/nvim/plugged/ale/ale_linters/help/writegood.vim
```
</details>

**Comment by blueyed** [comment]
Try Neovim master and/or Vim.
Likely due to https://github.com/neovim/neovim/issues/3757 (fixed in Neovim master).

Related: https://github.com/davidhalter/jedi-vim/pull/652

FWIW I've started playing around with using floating windows (only Neovim for now).

**Comment by davidhalter** [comment]
@ diazgilberto Please check again if it still happens for you.

**Comment by davidhalter** [comment]
Same issue as #493. We are trying to get rid of changing the buffer for this feature and are trying to use floating windows.
