### ISSUE TITLE
[jedi-vim]could not import the "jedi" Python module: ModuleNotFoundError: No module named '_posixsubprocess'

### ISSUE THREAD

**Issue by CengSin** [davidhalter/jedi-vim#935]
### Issue

vim already installed jedi-vim and pip installed jedi，vim throw this error info when i use vim open *.py file .

：JediDebugInfo

```shell
#### Jedi-vim debug information


##### jedi-vim version
xsubprocess' (in function jedi#init_python[4]..<SNR>62_init_python[27]..jedi#setup_python_imports，第 27 行). See :
messages and/or :JediDebugInfo for more information.
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 0.10.0
 - jedi git submodule status:  60415033b40bcef939d2a5378e2eff7b563265c5 pythonx/jedi (v0.14.1)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.4 (default, Jul 11 2019, 09:35:14), [GCC 9.1.0]`
 - global site module: `/mingw64/lib/python3.7/site.py`
ERROR: could not import the "jedi" Python module: ModuleNotFoundError: No module named '_posixsubprocess'
  Traceback (most recent call last):
    File "/c/Users/15262/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/c/Users/15262/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 38, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/c/Users/15262/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/c/Users/15262/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
      from parso.parser import ParserSyntaxError
    File "/c/Users/15262/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 26, in <module>
      from parso import tree
    File "/c/Users/15262/.vim/bundle/jedi-vim/pythonx/parso/parso/tree.py", line 3, in <module>
      from parso._compatibility import utf8_repr, encoding, py_version
    File "/c/Users/15262/.vim/bundle/jedi-vim/pythonx/parso/parso/_compatibility.py", line 6, in <module>
      import platform
    File "/mingw64/lib/python3.7/platform.py", line 116, in <module>
      import sys, os, re, subprocess
    File "/mingw64/lib/python3.7/subprocess.py", line 152, in <module>
      import _posixsubprocess

##### Settings

  omnifunc=python3complete#Complete
        最近修改于 /usr/share/vim/vim81/ftplugin/python.vim line 41
  completeopt=menuone,longest,preview
        最近修改于 ~/.vim/bundle/jedi-vim/plugin/jedi.vim line 36
```

```

### Steps to reproduce

i just open a py file

### environment

window10 for git-windows-sdk

**Comment by CengSin** [comment]
this work when i use msys2.exe。i close this issue.
