### ISSUE TITLE
anaconda3 with jedi-vim, ImportError

### ISSUE THREAD

**Issue by Poro-lab** [davidhalter/jedi-vim#946]
### Issue and Steps to reproduce

I have anaconda3 python distribution installed on Manjaro Linux where I work on my projects. I use Vim as my text editor and jedi-vim plugin (which I installed with a recommended method, Vundle).

I also work with this combination on my Linux Mint machine where everything works fine.

When working in the anaconda environment, jedi-vim raises the following ImportError:

##### jedi-vim version

 - jedi-vim git version: 0.10.0-3-g4f2499e
 - jedi git submodule status:  005f69390c4b1a3b864e7373cfcbdaf95e65411d pythonx/jedi (v0.15.1)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.4 (default, Jul 16 2019, 07:12:58), [GCC 9.1.0]`
 - global site module: `/home/<username>/anaconda3/lib/python3.7/site.py`
ERROR: could not import the "jedi" Python module: ImportError: /home/<username>/anaconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
  Traceback (most recent call last):
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 38, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
      from parso.parser import ParserSyntaxError
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 26, in <module>
      from parso import tree
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/tree.py", line 3, in <module>
      from parso._compatibility import utf8_repr, encoding, py_version
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/_compatibility.py", line 6, in <module>
      import platform
    File "/home/<username>/anaconda3/lib/python3.7/platform.py", line 116, in <module>
      import sys, os, re, subprocess
    File "/home/<username>/anaconda3/lib/python3.7/subprocess.py", line 152, in <module>
      import _posixsubprocess

##### Settings

```
  omnifunc=python3complete#Complete
	Last set from /usr/share/vim/vim81/ftplugin/python.vim line 41
  completeopt=menuone,longest,preview
	Last set from /usr/share/vim/vimfiles/plugin/jedi.vim line 31
```

#### :version
```

VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 21 2019 18:00:45)
Included patches: 1-1906
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +cursorbind        +insert_expand     +mouse_sgr         +ruby/dyn          +title
+arabic            +cursorshape       +job               -mouse_sysmouse    +scrollbind        -toolbar
+autocmd           +dialog_con        +jumplist          +mouse_urxvt       +signs             +user_commands
+autochdir         +diff              +keymap            +mouse_xterm       +smartindent       +vartabs
-autoservername    +digraphs          +lambda            +multi_byte        -sound             +vertsplit
-balloon_eval      -dnd               +langmap           +multi_lang        +spell             +virtualedit
+balloon_eval_term -ebcdic            +libcall           -mzscheme          +startuptime       +visual
-browse            +emacs_tags        +linebreak         +netbeans_intg     +statusline        +visualextra
++builtin_terms    +eval              +lispindent        +num64             -sun_workshop      +viminfo
+byte_offset       +ex_extra          +listcmds          +packages          +syntax            +vreplace
+channel           +extra_search      +localmap          +path_extra        +tag_binary        +wildignore
+cindent           -farsi             +lua/dyn           +perl/dyn          -tag_old_static    +wildmenu
-clientserver      +file_in_path      +menu              +persistent_undo   -tag_any_white     +windows
-clipboard         +find_in_path      +mksession         +postscript        +tcl/dyn           +writebackup
+cmdline_compl     +float             +modify_fname      +printer           +termguicolors     -X11
+cmdline_hist      +folding           +mouse             +profile           +terminal          -xfontset
+cmdline_info      -footer            -mouseshape        +python/dyn        +terminfo          -xim
+comments          +fork()            +mouse_dec         +python3/dyn       +termresponse      -xpm
+conceal           +gettext           +mouse_gpm         +quickfix          +textobjects       -xsmp
+cryptv            -hangul_input      -mouse_jsbterm     +reltime           +textprop          -xterm_clipboard
+cscope            +iconv             +mouse_netterm     +rightleft         +timers            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lelf -lnsl    -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.30/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.30/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm     
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"to_grayscale.py" 12L, 138C
jedi-vim error: jedi#setup_python_imports: ImportError: /home/<username>/anaconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
  Traceback (most recent call last):
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 38, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
      from parso.parser import ParserSyntaxError
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 26, in <module>
      from parso import tree
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/tree.py", line 3, in <module>
      from parso._compatibility import utf8_repr, encoding, py_version
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/_compatibility.py", line 6, in <module>
      import platform
    File "/home/<username>/anaconda3/lib/python3.7/platform.py", line 116, in <module>
      import sys, os, re, subprocess
    File "/home/<username>/anaconda3/lib/python3.7/subprocess.py", line 152, in <module>
      import _posixsubprocess
Error detected while processing function jedi#init_python[11]..<SNR>30_display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: /home/<username>/anaconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise (in function jedi#init_python[4]..<SNR>30_init_python[27]..jedi#setup_python_imports, line 27). See :messages and/or :JediDebugInfo for more information.
jedi-vim error: jedi#setup_python_imports: ImportError: /home/<username>/anaconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise
  Traceback (most recent call last):
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 38, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 41, in <module>
      from parso.parser import ParserSyntaxError
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/parser.py", line 26, in <module>
      from parso import tree
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/tree.py", line 3, in <module>
      from parso._compatibility import utf8_repr, encoding, py_version
    File "/home/<username>/.vim/bundle/jedi-vim/pythonx/parso/parso/_compatibility.py", line 6, in <module>
      import platform
    File "/home/<username>/anaconda3/lib/python3.7/platform.py", line 116, in <module>
      import sys, os, re, subprocess
    File "/home/<username>/anaconda3/lib/python3.7/subprocess.py", line 152, in <module>
      import _posixsubprocess
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: /home/<username>/anaconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise (in function jedi#init_python[4]..<SNR>30_init_python[27]..jedi#setup_python_imports, line 27). See :messages and/or :JediDebugInfo for more information.
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 21 2019 18:00:45)
```

<details><summary>:scriptnames</summary>

```
  1: /etc/vimrc
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: ~/.vimrc
  4: /usr/share/vim/vim81/ftoff.vim
  5: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
  6: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
  7: /usr/share/vim/vim81/filetype.vim
  8: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
  9: /usr/share/vim/vim81/ftplugin.vim
 10: /usr/share/vim/vim81/indent.vim
 11: /usr/share/vim/vim81/syntax/syntax.vim
 12: /usr/share/vim/vim81/syntax/synload.vim
 13: /usr/share/vim/vim81/syntax/syncolor.vim
 14: ~/.vim/bundle/vim-colorschemes/colors/Monokai.vim
 15: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 16: /usr/share/vim/vimfiles/plugin/jedi.vim
 17: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
 18: /usr/share/vim/vim81/plugin/gzip.vim
 19: /usr/share/vim/vim81/plugin/logiPat.vim
 20: /usr/share/vim/vim81/plugin/manpager.vim
 21: /usr/share/vim/vim81/plugin/matchparen.vim
 22: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 23: /usr/share/vim/vim81/plugin/rrhelper.vim
 24: /usr/share/vim/vim81/plugin/spellfile.vim
 25: /usr/share/vim/vim81/plugin/tarPlugin.vim
 26: /usr/share/vim/vim81/plugin/tohtml.vim
 27: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 28: /usr/share/vim/vim81/plugin/zipPlugin.vim
 29: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 30: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 31: /usr/share/vim/vimfiles/ftplugin/python/jedi.vim
 32: /usr/share/vim/vim81/ftplugin/python.vim
 33: /usr/share/vim/vimfiles/after/ftplugin/python/jedi.vim
 34: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 35: /usr/share/vim/vim81/indent/python.vim
 36: /usr/share/vim/vim81/syntax/python.vim
 37: /usr/share/vim/vimfiles/after/syntax/python.vim
 38: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
```
</details>

**Comment by blueyed** [comment]
> ERROR: could not import the "jedi" Python module: ImportError: /home//anaconda3/lib/python3.7/lib-dynload/_posixsubprocess.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _Py_write_noraise

Looks like a broken Python installation.
I guess `import subprocess` fails there already without jedi-vim, when using the "python" that `:py3 import sys; print(sys.executable)` displays outside of Vim, no?

**Comment by blueyed** [comment]
Related: https://github.com/davidhalter/jedi-vim/issues/946, https://github.com/davidhalter/jedi-vim/issues/929 etc.

**Comment by Poro-lab** [comment]
I typed the vim command `:py3 import sys; print(sys.executable).` It gave an output of `/home/<username>/anaconda3/bin/python3` Then I tried in a shell outside of vim the command `python /home/<username>/anaconda3/bin/python3` which gave an output:
`File "/home/<username>/anaconda3/bin/python3", line 1
SyntaxError: Non-UTF-8 code starting with '\xa1' in file /home/<username>/anaconda3/bin/python3 on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details`

Did I understand correctly what you meant? Sorry, noob here :D

**Comment by blueyed** [comment]
Almost.. instead of `python /home/<username>/anaconda3/bin/python3` you should run only `/home/<username>/anaconda3/bin/python3`.

Try `/home/<username>/anaconda3/bin/python3 -c "import subprocess"` directly.

**Comment by Poro-lab** [comment]
Tried both. No errors. I also reinstalled anaconda3 and all of my vim -plugins with Vundle. Same issue. And I have no problems with my Linux Mint machine, only with this arch based Manjaro distribution.

**Comment by blueyed** [comment]
Ah.. since you're using Vim the Python is linked therein (thought about Neovim, where it's the external process really).

You might want to try Neovim instead, or fix / re-install the Vim installation.
You can try using e.g. `ldd /path/to/vim` to see where it links against.

**Comment by blueyed** [comment]
Also search the existing issues for hints / solutions / fixes.
