### ISSUE TITLE
ImportError: cannot import name _remove_dead_weakref

### ISSUE THREAD

**Issue by aagnone3** [davidhalter/jedi-vim#951]
### Issue

I'm getting an import error on a fresh install of jedi-vim without any custom settings.

I've read somewhat related issues on `import _posixsubprocess` failing, but note the following:
- import issue is `import jedi`
- importing outside of vim is successful (see screenshot below)
- importing inside vim via `:python import jedi` returns the import error
    - `:python import sys; print sys.executable` returns `/Users/aagnone/github/brew/brew/opt/python@2/bin/python2.7`, which is the claimed executable by the output of jedi's debug info.

Some additional info to help in debugging the output below:
![image](https://user-images.githubusercontent.com/10716867/65531521-16de3e80-dec8-11e9-9b2e-55912445a041.png)

### Steps to reproduce
Install jedi-vim (I tried both with Vundle and the listed python executables pip)
vim temp.py

Please provide the `minimal.vimrc` you have used here, too.
```
" placed in ~/.vim/bundle/jedi-vim/
set nocompatible

let script_dir = fnamemodify(expand('<sfile>'), ':h')
let &runtimepath .= ','.script_dir.','.script_dir.'/after'

" Put your config changes here.
" let g:jedi#show_call_signatures=1

syntax on
filetype plugin indent on
```

##### jedi-vim version

 - jedi-vim git version: 0.10.0-5-g50abb5e
 - jedi git submodule status:  005f69390c4b1a3b864e7373cfcbdaf95e65411d pythonx/jedi (v0.15.1)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 2 to access Jedi.
 - global sys.executable: `/Users/aagnone/github/brew/brew/opt/python@2/bin/python2.7`
 - global sys.version: `2.7.10 (default, Feb 22 2019, 21:55:15), [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]`
 - global site module: `/Users/aagnone/github/brew/brew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc`
ERROR: could not import the "jedi" Python module: ImportError: cannot import name _remove_dead_weakref
  Traceback (most recent call last):
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 38, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 42, in <module>
      from parso.grammar import Grammar, load_grammar
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/grammar.py", line 7, in <module>
      from parso.python.diff import DiffParser
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/python/diff.py", line 11, in <module>
      import logging
    File "/Users/aagnone/github/brew/brew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in <module>
      import sys, os, time, cStringIO, traceback, warnings, weakref, collections
    File "/Users/aagnone/github/brew/brew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
      from _weakref import (

##### Settings

```
  omnifunc=pythoncomplete#Complete
	Last set from /Applications/MacVim.app/Contents/Resources/vim/runtime/ftplugin/python.vim line 43
  completeopt=menuone,longest,preview
	Last set from ~/.vim/bundle/jedi-vim/plugin/jedi.vim line 36
```

#### :version
```

VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 28 2019 01:07:30)
macOS version
Included patches: 1-1722
Compiled by travis@Traviss-Mac.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +channel           +cscope            +ex_extra          -gettext           +linebreak         +mouse_dec         -mzscheme          +profile           -sound             +termguicolors     +user_commands     +windows           
+arabic            +cindent           +cursorbind        +extra_search      -hangul_input      +lispindent        -mouse_gpm         +netbeans_intg     +python/dyn        +spell             +terminal          +vartabs           +writebackup       
+autocmd           +clientserver      +cursorshape       -farsi             +iconv             +listcmds          -mouse_jsbterm     +num64             +python3/dyn       +startuptime       +terminfo          +vertsplit         -X11               
+autochdir         +clipboard         +dialog_con_gui    +file_in_path      +insert_expand     +localmap          +mouse_netterm     +odbeditor         +quickfix          +statusline        +termresponse      +virtualedit       -xfontset          
-autoservername    +cmdline_compl     +diff              +find_in_path      +job               +lua/dyn           +mouse_sgr         +packages          +reltime           -sun_workshop      +textobjects       +visual            +xim               
+balloon_eval      +cmdline_hist      +digraphs          +float             +jumplist          +menu              -mouse_sysmouse    +path_extra        +rightleft         +syntax            +textprop          +visualextra       -xpm               
+balloon_eval_term +cmdline_info      +dnd               +folding           +keymap            +mksession         +mouse_urxvt       +perl/dyn          +ruby/dyn          +tag_binary        +timers            +viminfo           -xsmp              
+browse            +comments          -ebcdic            -footer            +lambda            +modify_fname      +mouse_xterm       +persistent_undo   +scrollbind        -tag_old_static    +title             +vreplace          -xterm_clipboard   
++builtin_terms    +conceal           +emacs_tags        +fork()            +langmap           +mouse             +multi_byte        +postscript        +signs             -tag_any_white     +toolbar           +wildignore        -xterm_save        
+byte_offset       +cryptv            +eval              +fullscreen        +libcall           +mouseshape        +multi_lang        +printer           +smartindent       -tcl               +transparency      +wildmenu          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE 
```

#### :messages
```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
jedi-vim error: jedi#setup_python_imports: ImportError: cannot import name _remove_dead_weakref
  Traceback (most recent call last):
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 38, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 42, in <module>
      from parso.grammar import Grammar, load_grammar
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/grammar.py", line 7, in <module>
      from parso.python.diff import DiffParser
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/python/diff.py", line 11, in <module>
      import logging
    File "/Users/aagnone/github/brew/brew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in <module>
      import sys, os, time, cStringIO, traceback, warnings, weakref, collections
    File "/Users/aagnone/github/brew/brew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
      from _weakref import (
Error detected while processing function jedi#init_python[11]..<SNR>74_display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: cannot import name _remove_dead_weakref (in function jedi#init_python[4]..<SNR>74_init_python[27]..jedi#setup_python_imports, line 27). See :messages and/or :JediDebugInfo for more information.
jedi-vim error: jedi#setup_python_imports: ImportError: cannot import name _remove_dead_weakref
  Traceback (most recent call last):
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py", line 38, in <module>
      from jedi.api import Script, Interpreter, set_debug_function, \
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/jedi/jedi/api/__init__.py", line 16, in <module>
      import parso
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/__init__.py", line 42, in <module>
      from parso.grammar import Grammar, load_grammar
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/grammar.py", line 7, in <module>
      from parso.python.diff import DiffParser
    File "/Users/aagnone/.vim/bundle/jedi-vim/pythonx/parso/parso/python/diff.py", line 11, in <module>
      import logging
    File "/Users/aagnone/github/brew/brew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 26, in <module>
      import sys, os, time, cStringIO, traceback, warnings, weakref, collections
    File "/Users/aagnone/github/brew/brew/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
      from _weakref import (
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: cannot import name _remove_dead_weakref (in function jedi#init_python[4]..<SNR>74_init_python[27]..jedi#setup_python_imports, line 27). See :messages and/or :JediDebugInfo for more information.
[flake8] [W291] trailing whitespace
2 fewer lines; before #1  2 seconds ago
[flake8] [W291] trailing whitespace
Already at oldest change
Already at oldest change
[flake8] [W391] blank line at end of file
search hit BOTTOM, continuing at TOP
E486: Pattern not found: :redir @+> | silent verb JediDebugInfo | redir END
```

<details><summary>:scriptnames</summary>

```
  1: /Applications/MacVim.app/Contents/Resources/vim/vimrc
  2: ~/.vimrc
  3: ~/.vimrc_plugins
  4: ~/.vim/bundle/Vundle.vim/autoload/vundle.vim
  5: ~/.vim/bundle/Vundle.vim/autoload/vundle/config.vim
  6: /Applications/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
  7: /Applications/MacVim.app/Contents/Resources/vim/runtime/ftplugin.vim
  8: /Applications/MacVim.app/Contents/Resources/vim/runtime/indent.vim
  9: ~/.vimrc_awesomevim
 10: /Applications/MacVim.app/Contents/Resources/vim/runtime/delmenu.vim
 11: /Applications/MacVim.app/Contents/Resources/vim/runtime/menu.vim
 12: /Applications/MacVim.app/Contents/Resources/vim/runtime/lang/menu_en_gb.latin1.vim
 13: /Applications/MacVim.app/Contents/Resources/vim/runtime/lang/menu_en_gb.utf-8.vim
 14: /Applications/MacVim.app/Contents/Resources/vim/runtime/autoload/paste.vim
 15: /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/syntax.vim
 16: /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/synload.vim
 17: /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/syncolor.vim
 18: ~/.vim/bundle/vim-colorschemes/colors/monokai-chris.vim
 19: ~/.vimrc_aagnone
 20: ~/.vimrc_mac
 21: ~/.vim/plugin/aw.vim
 22: ~/.vim/plugin/aww.vim
 23: ~/.vim/plugin/reindex.vim
 24: ~/.vim/plugin/team_tracking.vim
 25: ~/.vim/bundle/vim-tmux-navigator/plugin/tmux_navigator.vim
 26: ~/.vim/bundle/ale/plugin/ale.vim
 27: ~/.vim/bundle/ale/autoload/ale/events.vim
 28: ~/.vim/bundle/jedi-vim/plugin/jedi.vim
 29: ~/.vim/bundle/supertab/plugin/supertab.vim
 30: ~/.vim/bundle/vimwiki/plugin/vimwiki.vim
 31: ~/.vim/bundle/vimwiki/autoload/vimwiki/vars.vim
 32: ~/.vim/bundle/vimwiki/autoload/vimwiki/u.vim
 33: ~/.vim/bundle/nerdtree/plugin/NERD_tree.vim
 34: ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
 35: ~/.vim/bundle/nerdtree/lib/nerdtree/path.vim
 36: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_controller.vim
 37: ~/.vim/bundle/nerdtree/lib/nerdtree/menu_item.vim
 38: ~/.vim/bundle/nerdtree/lib/nerdtree/key_map.vim
 39: ~/.vim/bundle/nerdtree/lib/nerdtree/bookmark.vim
 40: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_file_node.vim
 41: ~/.vim/bundle/nerdtree/lib/nerdtree/tree_dir_node.vim
 42: ~/.vim/bundle/nerdtree/lib/nerdtree/opener.vim
 43: ~/.vim/bundle/nerdtree/lib/nerdtree/creator.vim
 44: ~/.vim/bundle/nerdtree/lib/nerdtree/flag_set.vim
 45: ~/.vim/bundle/nerdtree/lib/nerdtree/nerdtree.vim
 46: ~/.vim/bundle/nerdtree/lib/nerdtree/ui.vim
 47: ~/.vim/bundle/nerdtree/lib/nerdtree/event.vim
 48: ~/.vim/bundle/nerdtree/lib/nerdtree/notifier.vim
 49: ~/.vim/bundle/nerdtree/autoload/nerdtree/ui_glue.vim
 50: ~/.vim/bundle/nerdtree/nerdtree_plugin/exec_menuitem.vim
 51: ~/.vim/bundle/nerdtree/nerdtree_plugin/fs_menu.vim
 52: ~/.vim/bundle/nerdtree/nerdtree_plugin/vcs.vim
 53: ~/.vim/bundle/vim-devicons/nerdtree_plugin/webdevicons.vim
 54: ~/.vim/bundle/vim-devicons/plugin/webdevicons.vim
 55: ~/.vim/bundle/tagbar/plugin/tagbar.vim
 56: ~/.vim/bundle/vim-airline/plugin/airline.vim
 57: ~/.vim/bundle/vim-airline/autoload/airline/init.vim
 58: ~/.vim/bundle/vim-airline/autoload/airline/parts.vim
 59: ~/.vim/bundle/vim-airline/autoload/airline/util.vim
 60: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/getscriptPlugin.vim
 61: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/gzip.vim
 62: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/logiPat.vim
 63: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/manpager.vim
 64: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/matchparen.vim
 65: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/netrwPlugin.vim
 66: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/rrhelper.vim
 67: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/spellfile.vim
 68: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/tarPlugin.vim
 69: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/tohtml.vim
 70: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/vimballPlugin.vim
 71: /Applications/MacVim.app/Contents/Resources/vim/runtime/plugin/zipPlugin.vim
 72: ~/.vim/bundle/vim-pydocstring/ftplugin/python/pydocstring.vim
 73: ~/.vim/bundle/jedi-vim/ftplugin/python/jedi.vim
 74: ~/.vim/bundle/jedi-vim/autoload/jedi.vim
 75: /Applications/MacVim.app/Contents/Resources/vim/runtime/ftplugin/python.vim
 76: ~/.vim/bundle/jedi-vim/after/ftplugin/python/jedi.vim
 77: ~/.vim/bundle/indentpython.vim/indent/python.vim
 78: ~/.vim/bundle/vim-python-pep8-indent/indent/python.vim
 79: /Applications/MacVim.app/Contents/Resources/vim/runtime/indent/python.vim
 80: /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/python.vim
 81: ~/.vim/bundle/jedi-vim/after/syntax/python.vim
 82: ~/.vim/bundle/vim-airline/autoload/airline/extensions.vim
 83: ~/.vim/bundle/vim-airline/autoload/airline/extensions/quickfix.vim
 84: ~/.vim/bundle/vim-airline/autoload/airline.vim
 85: ~/.vim/bundle/vim-airline/autoload/airline/extensions/netrw.vim
 86: ~/.vim/bundle/vim-airline/autoload/airline/extensions/term.vim
 87: ~/.vim/bundle/vim-airline/autoload/airline/section.vim
 88: ~/.vim/bundle/vim-airline/autoload/airline/highlighter.vim
 89: ~/.vim/bundle/vim-airline/autoload/airline/extensions/tagbar.vim
 90: ~/.vim/bundle/vim-airline/autoload/airline/extensions/vista.vim
 91: ~/.vim/bundle/vim-airline/autoload/airline/extensions/ale.vim
 92: ~/.vim/bundle/vim-airline/autoload/airline/extensions/whitespace.vim
 93: ~/.vim/bundle/vim-airline/autoload/airline/extensions/wordcount.vim
 94: ~/.vim/bundle/vim-airline/autoload/airline/extensions/keymap.vim
 95: ~/.vim/bundle/vim-airline/autoload/airline/themes/dark.vim
 96: ~/.vim/bundle/vim-airline/autoload/airline/themes.vim
 97: ~/.vim/bundle/vim-airline/autoload/airline/builder.vim
 98: ~/.vim/bundle/vim-airline/autoload/airline/extensions/default.vim
 99: ~/.vim/bundle/ale/autoload/ale.vim
100: ~/.vim/bundle/ale/autoload/ale/util.vim
101: ~/.vim/bundle/ale/autoload/ale/linter.vim
102: ~/.vim/bundle/ale/ale_linters/python/bandit.vim
103: ~/.vim/bundle/ale/ale_linters/python/flake8.vim
104: ~/.vim/bundle/ale/ale_linters/python/mypy.vim
105: ~/.vim/bundle/ale/ale_linters/python/prospector.vim
106: ~/.vim/bundle/ale/ale_linters/python/pycodestyle.vim
107: ~/.vim/bundle/ale/ale_linters/python/pydocstyle.vim
108: ~/.vim/bundle/ale/ale_linters/python/pyflakes.vim
109: ~/.vim/bundle/ale/ale_linters/python/pylama.vim
110: ~/.vim/bundle/ale/ale_linters/python/pylint.vim
111: ~/.vim/bundle/ale/ale_linters/python/pyls.vim
112: ~/.vim/bundle/ale/ale_linters/python/pyre.vim
113: ~/.vim/bundle/ale/ale_linters/python/vulture.vim
114: ~/.vim/bundle/ale/autoload/ale/engine.vim
115: ~/.vim/bundle/ale/autoload/ale/command.vim
116: ~/.vim/bundle/ale/autoload/ale/history.vim
117: ~/.vim/bundle/ale/autoload/ale/semver.vim
118: ~/.vim/bundle/ale/autoload/ale/job.vim
119: ~/.vim/bundle/ale/autoload/ale/cursor.vim
120: ~/.vim/bundle/tagbar/autoload/tagbar.vim
121: ~/.vim/bundle/tagbar/autoload/tagbar/debug.vim
122: ~/.vim/bundle/tagbar/autoload/tagbar/types/uctags.vim
123: ~/.vim/bundle/tagbar/autoload/tagbar/prototypes/typeinfo.vim
124: ~/.vim/bundle/ale/autoload/ale/statusline.vim
125: ~/.vim/bundle/vim-pydocstring/autoload/pydocstring.vim
126: ~/.vim/bundle/ale/autoload/ale/path.vim
127: ~/.vim/bundle/ale/autoload/ale/python.vim
128: ~/.vim/bundle/ale/autoload/ale/sign.vim
129: ~/.vim/bundle/ale/autoload/ale/list.vim
130: ~/.vim/bundle/ale/autoload/ale/highlight.vim
131: /Applications/MacVim.app/Contents/Resources/vim/runtime/ftplugin/qf.vim
132: /Applications/MacVim.app/Contents/Resources/vim/runtime/syntax/qf.vim
```
</details>

**Comment by davidhalter** [comment]
This still looks like a broken Python installation. Does `:PyJedi import logging` work?

**Comment by aagnone3** [comment]
That command isn't found. I'm assuming the initialization errors out before the `PyJedi` command can be defined.

**Comment by aagnone3** [comment]
I solved the issue using feedback [here](https://github.com/ycm-core/YouCompleteMe/issues/2883) to `brew uninstall python@2` to avoid conflicting python installations.

Also, the command for above is `:PythonJedi import logging`
