### ISSUE TITLE
fail to call goto_assignments_command

### ISSUE THREAD

**Issue by huzilin** [davidhalter/jedi-vim#962]
### Issue

fail to call goto_assignments_command

```
Traceback (most recent call last):
  File "~/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "~/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 404, in goto
    vim.current.window.cursor = d.line, d.column
vim.error: cursor position outside buffer
```
### Output of “:verbose JediDebugInfo”

```
#### Jedi-vim debug information

##### jedi-vim version

 - jedi-vim git version: 0.10.0-8-g08f13af
 - jedi git submodule status:  005f69390c4b1a3b864e7373cfcbdaf95e65411d pythonx/jedi (v0.15.1)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.executable: `/usr/local/bin/vim`
 - global sys.version: `3.7.4 (default, Oct 30 2019, 15:12:19), [Clang 11.0.0 (clang-1100.0.33.8)]`
 - global site module: `/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site.py`

##### Jedi

 - path: `~/.vim/bundle/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.15.1

##### Jedi environment: <Environment: 3.5.1 in ~/workdir/python3.5.1_env>

#### :version

VIM - Vi IMproved 8.1 (2018 May 17, compiled Jul  1 2018 23:39:42)
macOS version
Included patches: 1-100
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cryptv            -footer            +mksession         +path_extra        +syntax            +viminfo
+arabic            +cscope            +fork()            +modify_fname      +perl              +tag_binary        +vreplace
+autocmd           +cursorbind        -gettext           +mouse             +persistent_undo   +tag_old_static    +wildignore
-autoservername    +cursorshape       -hangul_input      -mouseshape        +postscript        -tag_any_white     +wildmenu
-balloon_eval      +dialog_con        +iconv             +mouse_dec         +printer           -tcl               +windows
+balloon_eval_term +diff              +insert_expand     -mouse_gpm         +profile           +termguicolors     +writebackup
-browse            +digraphs          +job               -mouse_jsbterm     -python            +terminal          -X11
++builtin_terms    -dnd               +jumplist          +mouse_netterm     +python3           +terminfo          -xfontset
+byte_offset       -ebcdic            +keymap            +mouse_sgr         +quickfix          +termresponse      -xim
+channel           +emacs_tags        +lambda            -mouse_sysmouse    +reltime           +textobjects       -xpm
+cindent           +eval              +langmap           +mouse_urxvt       +rightleft         +timers            -xsmp
-clientserver      +ex_extra          +libcall           +mouse_xterm       +ruby              +title             -xterm_clipboard
+clipboard         +extra_search      +linebreak         +multi_byte        +scrollbind        -toolbar           -xterm_save
+cmdline_compl     +farsi             +lispindent        +multi_lang        +signs             +user_commands
+cmdline_hist      +file_in_path      +listcmds          -mzscheme          +smartindent       +vertsplit
+cmdline_info      +find_in_path      +localmap          +netbeans_intg     +startuptime       +virtualedit
+comments          +float             +lua               +num64             +statusline        +visual
+conceal           +folding           +menu              +packages          -sun_workshop      +visualextra
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib
  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.13 -fstack-prot
ector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/l
ocal/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.1
-lobjc
```

**Comment by blueyed** [comment]
Yes, that might happen with wrong results from Jedi IIRC (likely I've filed it there already and/or here).
Do you have steps to reproduce it?

**Comment by huzilin** [comment]
## test1.py

```python
# -*- coding: utf-8 -*-

def log(func):
    def wrapper(*args, **kw):
        print("call %s():" % func.__name__)
        return func(*args, **kw)

    return wrapper


class Base:
    @log
    def f1(self):
        pass
```

### test2.py
```
# -*- coding: utf-8 -*-

from test1 import Base


class C1(Base):
    def f3(self):
        self.f1() .     # call goto_assignments_command in this place
```

**Comment by blueyed** [comment]
Thanks for the reproducer!  (have not tried it (yet))
But the issue I've meant is https://github.com/davidhalter/jedi/issues/1396

**Comment by davidhalter** [comment]
I can unfortunately not reproduce. Did you do it without the comment or with it? Also which command are you using? `\g`?

**Comment by davidhalter** [comment]
Ok, my bad. I realized that I never did it on the name. Thanks for the reproduction code!

**Comment by davidhalter** [comment]
The original issue was fixed on latest jedi-vim (master), it was probably davidhalter/jedi#1396 that fixed this.

However goto still didn't work. I therefore pushed an additional fix in Jedi.
