### ISSUE TITLE
usages: TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by blueyed** [davidhalter/jedi-vim#965]
Also seems to happen when attempting to close the quickfix Window.

I also noticed this error when trying to use `usages` on something imported as just the function name:

```
from ..xplane_helpers import floatToStr, FLOAT_PRECISION, logger
...
# place cursor on floatToStr, press CTRL-G to use usages, get message instead of result
                        floatToStr(axis_angle_vec3_x[0]),
```

```
Traceback (most recent call last):
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi_vim.py", line 192, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi_vim.py", line 510, in usages
    show_goto_multi_results(definitions, "usages")
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi_vim.py", line 461, in show_goto_multi_results
    qf_title += ": " + current_def.full_name
TypeError: can only concatenate str (not "NoneType") to str
```

I'm not sure if this is the same bug or different.

`go to definition` worked on that same symbol, however.

_Originally posted by @tngreene in https://github.com/davidhalter/jedi-vim/issues/964#issuecomment-553489395_

**Comment by davidhalter** [comment]
It would be really interesting if @tngreene could run something like:

```
import jedi
print(jedi.Script('from ..xplane_helpers import floatToStr').goto_assignments(follow_imports=True))
```

This could show us what is actually happening there with Jedi.

In general there are are reasons why stuff can have a full_name that is None, but in this case I'm not sure it makes sense. It would therefore be interesting to understand this case.

**Comment by tngreene** [comment]
Like, open up that source file and run the above as

`python3 import jedi; print(...etc)`?

When I do that I get back `[]`

**Comment by davidhalter** [comment]
Oh sorry, I did not read this properly. Do it with 

```
import jedi
print(jedi.Script('from ..xplane_helpers import floatToStr').usages())
```

instead. Not sure if that works, but it's at least closter to what you did.

**Comment by tngreene** [comment]
No good:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\api\__init__.py", line 349, in usages
    return _usages(**kwargs)
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\api\__init__.py", line 343, in _usages
    names = usages.usages(self._get_module(), tree_name)
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\usages.py", line 46, in usages
    new = _find_names(m, name_leaf)
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\usages.py", line 32, in _find_names
    found_names = set(name.goto())
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\names.py", line 106, in goto
    return self.parent_context.evaluator.goto(self.parent_context, self.tree_name, **kwargs)
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\__init__.py", line 311, in goto
    module_names = imports.infer_import(context, name, is_goto=True)
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\cache.py", line 42, in wrapper
    rv = function(obj, *args, **kwargs)
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\imports.py", line 79, in infer_import
    module_context, import_node.level)
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\imports.py", line 207, in __init__
    base = module_context.py__package__()
  File "C:\Users\Ted\.vim\bundle\jedi-vim\pythonx\jedi\jedi\evaluate\context\module.py", line 234, in py__package__
    return self.string_names[:-1]
TypeError: 'NoneType' object is not subscriptable
```

The file in question is [this](https://github.com/X-Plane/XPlane2Blender/blob/399-blender-28-support/io_xplane2blender/xplane_types/xplane_light.py), in case it matters. `floatToStr` is in [xplane_helpers.py](https://github.com/X-Plane/XPlane2Blender/blob/399-blender-28-support/io_xplane2blender/xplane_helpers.py)

**Comment by davidhalter** [comment]
Are you on Jedi master? In any case this looks like a Jedi bug :)

**Comment by tngreene** [comment]
I was not on master. What branch or commit should I try instead? master?

**Comment by davidhalter** [comment]
Can you retry on Jedi 0.15.2? A few bugs were fixed.

**Comment by tngreene** [comment]
Looks like I'm using that one:
```
C:\Users\Ted\.vim\bundle\jedi-vim>git submodule
 afbd8cad8938331ff89dac34126b4960809dc75b pythonx/jedi (v0.15.2)
 fb010f2b5d67a7b284962e1059e4ebadf87792d0 pythonx/parso (v0.5.2)
```

**Comment by tngreene** [comment]
And it looks like it is working! Great! Will comment again if I start seeing the message again! Now on to the next one.
