### ISSUE TITLE
Unable to use jedi-vim

### ISSUE THREAD

**Issue by sc-1123** [davidhalter/jedi-vim#975]
I'm using Vim 8.2 on windows, use [vim-plug](https://github.com/junegunn/vim-plug) to install jedi-vim. But I can't see the auto filling.
What's wrong?

**Comment by davidhalter** [comment]
Please fill out the form to have enough information to debug your issue. You have intentionally ignored it, by deleting the form when creating a new issue. I'm just pointing it out, because the form is there for a reason. It saves us a lot of time and questions if we have it.

We are happy to reopen this issue if you add the necessary information.

**Comment by jayli** [comment]
My vim 8.2 has the same problem. After updating vim 8.1 → 8.2. I got this error message while startup vim with a python file.

```
jedi-vim error: jedi#setup_python_imports: ImportError: No module named jedi
  Traceback (most recent call last):
    File "/Users/bachi/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
Error detected while processing function jedi#init_python[11]..<SNR>95_display_exception:
line   19:
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: No module named jedi (in function jedi#init_python[4]..<SNR>95_init_pytho
n[27]..jedi#setup_python_imports, line 27). See :messages and/or :JediDebugInfo for more information.
jedi-vim error: jedi#setup_python_imports: ImportError: No module named jedi
  Traceback (most recent call last):
    File "/Users/bachi/.vim/bundle/jedi-vim/pythonx/jedi_vim.py", line 112, in <module>
      import jedi
Error: jedi-vim failed to initialize Python: jedi#setup_python_imports: ImportError: No module named jedi (in function jedi#init_python[4]..<SNR>95_init_pytho
n[27]..jedi#setup_python_imports, line 27). See :messages and/or :JediDebugInfo for more information.
```

I have python 2 & 3 installed.

```
░ bachi ~ » vim --version | grep python
+cmdline_info      +libcall           +python/dyn        +visual
+comments          +linebreak         +python3/dyn       +visualextra
```

Jedi is already installed correctly. 

```
░ bachi ~/python/dump ±master » pip2 search jedi
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
jedi-language-server (0.4.0)      - A language server for Jedi!
jedi (0.15.2)                     - An autocompletion tool for Python that can be used for text editors.
  INSTALLED: 0.15.2 (latest)
pybuilder_jedi_plugin (0.0.3)     - Lint python sources with the jedi linter (experimental)
py3-dependency-graph (0.0.5)      - A simple jedi based python3 dependency analysis tool
SDGraph (0.0.5)                   - A simple jedi based python3 dependency analysis tool
hotdoc_python_extension (0.8.90)  - An extension for hotdoc that parses python using the jedi module and napoleon from sphinx
░ bachi ~/python/dump ±master » python3 -m pip  search jedi                                                                                  1 ↵
jedi-language-server (0.4.0)      - A language server for Jedi!
jedi (0.15.2)                     - An autocompletion tool for Python that can be used for text editors.
  INSTALLED: 0.15.2 (latest)
pybuilder_jedi_plugin (0.0.3)     - Lint python sources with the jedi linter (experimental)
py3-dependency-graph (0.0.5)      - A simple jedi based python3 dependency analysis tool
SDGraph (0.0.5)                   - A simple jedi based python3 dependency analysis tool
hotdoc_python_extension (0.8.90)  - An extension for hotdoc that parses python using the jedi module and napoleon from sphinx
```

But `python -c "import jedi"` shows an error.

```
░ bachi ~/python/dump ±master » python -c "import jedi"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named jedi
░ bachi ~/python/dump ±master » python3 -c "import jedi"                                                                                     1 ↵
░ bachi ~/python/dump ±master » 
```

**Comment by davidhalter** [comment]
Open a new issue and fill out the form with all the debug info please.
